import test from 'node:test';
import assert from 'node:assert/strict';
import { tempRepo } from './helpers.js';
import { initStore,readState } from '../src/store.js';
import { extractAgentJson } from '../src/agent-team.js';
import { normalizeManagerPlan } from '../src/delivery.js';
import { addOwnerDecision,resolveOwnerDecision } from '../src/handover.js';

test('AI team JSON parser accepts fenced and plain structured decisions',()=>{assert.deepEqual(extractAgentJson('```json\n{"status":"READY"}\n```'),{status:'READY'});assert.deepEqual(extractAgentJson('prefix\n{"verdict":"APPROVE","summary":"ok"}\nsuffix'),{verdict:'APPROVE',summary:'ok'});assert.throws(()=>extractAgentJson('not-json'),/JSON/);});

test('manager plan normalizes IDs and rejects unsafe graph output',()=>{const state={tasks:[],profile:{}};const plan=normalizeManagerPlan({status:'PLAN',summary:'roadmap',tasks:[{id:'core 1',title:'Core',objective:'Implement core',acceptanceCriteria:['works'],dependsOn:[],risk:'LOW'},{id:'UI-2',title:'UI',objective:'Implement UI',acceptanceCriteria:['renders'],dependsOn:['CORE-1']}]},state);assert.equal(plan.tasks.length,2);assert.equal(plan.tasks[0].id,'CORE-1');assert.equal(plan.tasks[0].risk,'low');assert.deepEqual(plan.tasks[1].dependsOn,['CORE-1']);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'A',title:'A',acceptanceCriteria:['a'],dependsOn:['MISSING']}]},state),/unknown task/);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'A',title:'A',acceptanceCriteria:['a'],dependsOn:['B']},{id:'B',title:'B',acceptanceCriteria:['b'],dependsOn:['A']}]},state),/cycle/);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'A',title:'A',acceptanceCriteria:['a']},{id:'A',title:'Duplicate',acceptanceCriteria:['b']}]},state),/duplicate task id/);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'SELF',title:'Self',acceptanceCriteria:['a'],dependsOn:['SELF']}]},state),/cycle|depend on itself/);});

test('owner release gate authorizes only explicit approval',()=>{const root=tempRepo('owner-gate');initStore(root);const d=addOwnerDecision({gate:'release',title:'Release?',question:'Approve?',options:['approve','pause']},root);assert.equal(readState(root).delivery.state,'OWNER_DECISION_REQUIRED');resolveOwnerDecision(d.id,'approve','approved',root);const state=readState(root);assert.equal(state.delivery.authorizedGates.release,true);assert.equal(state.ownerDecisions[0].status,'RESOLVED');assert.equal(state.delivery.state,'PAUSED');});

test('owner replan resolution requests manager replan without granting gates',()=>{const root=tempRepo('owner-replan');initStore(root);const d=addOwnerDecision({title:'Repair exhausted',question:'Next?',options:['retry','replan','pause'],taskId:'TASK-1'},root);resolveOwnerDecision(d.id,'replan','re-evaluate implementation path',root);const state=readState(root);assert.equal(state.delivery.forceReplan,true);assert.deepEqual(state.delivery.authorizedGates,{});assert.equal(state.delivery.state,'PAUSED');});
