import test from 'node:test';
import assert from 'node:assert/strict';
import { tempRepo } from './helpers.js';
import { initStore,readState,addTasks,transition,replayStateFromJournal } from '../src/store.js';
import { extractAgentJson } from '../src/agent-team.js';
import { normalizeManagerPlan,applyReplacementLinks } from '../src/delivery.js';
import { addOwnerDecision,resolveOwnerDecision } from '../src/handover.js';
import { classifyProviderAvailability } from '../src/runner.js';
import { commandForPrompt,commandFor } from '../src/agents.js';

test('AI team JSON parser accepts fenced and plain structured decisions',()=>{assert.deepEqual(extractAgentJson('```json\n{"status":"READY"}\n```'),{status:'READY'});assert.deepEqual(extractAgentJson('prefix\n{"verdict":"APPROVE","summary":"ok"}\nsuffix'),{verdict:'APPROVE',summary:'ok'});assert.throws(()=>extractAgentJson('not-json'),/JSON/);});

test('manager plan normalizes IDs and rejects unsafe graph output',()=>{const state={tasks:[],profile:{}};const plan=normalizeManagerPlan({status:'PLAN',summary:'roadmap',tasks:[{id:'core 1',title:'Core',objective:'Implement core',acceptanceCriteria:['works'],dependsOn:[],risk:'LOW'},{id:'UI-2',title:'UI',objective:'Implement UI',acceptanceCriteria:['renders'],dependsOn:['CORE-1']}]},state);assert.equal(plan.tasks.length,2);assert.equal(plan.tasks[0].id,'CORE-1');assert.equal(plan.tasks[0].risk,'low');assert.deepEqual(plan.tasks[1].dependsOn,['CORE-1']);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'A',title:'A',acceptanceCriteria:['a'],dependsOn:['MISSING']}]},state),/unknown task/);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'A',title:'A',acceptanceCriteria:['a'],dependsOn:['B']},{id:'B',title:'B',acceptanceCriteria:['b'],dependsOn:['A']}]},state),/cycle/);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'A',title:'A',acceptanceCriteria:['a']},{id:'A',title:'Duplicate',acceptanceCriteria:['b']}]},state),/duplicate task id/);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'SELF',title:'Self',acceptanceCriteria:['a'],dependsOn:['SELF']}]},state),/cycle|depend on itself/);});

test('owner release gate authorizes only explicit approval',()=>{const root=tempRepo('owner-gate');initStore(root);const d=addOwnerDecision({gate:'release',title:'Release?',question:'Approve?',options:['approve','pause']},root);assert.equal(readState(root).delivery.state,'OWNER_DECISION_REQUIRED');resolveOwnerDecision(d.id,'approve','approved',root);const state=readState(root);assert.equal(state.delivery.authorizedGates.release,true);assert.equal(state.ownerDecisions[0].status,'RESOLVED');assert.equal(state.delivery.state,'PAUSED');});

test('owner replan resolution requests manager replan without granting gates',()=>{const root=tempRepo('owner-replan');initStore(root);const d=addOwnerDecision({title:'Repair exhausted',question:'Next?',options:['retry','replan','pause'],taskId:'TASK-1'},root);resolveOwnerDecision(d.id,'replan','re-evaluate implementation path',root);const state=readState(root);assert.equal(state.delivery.forceReplan,true);assert.deepEqual(state.delivery.authorizedGates,{});assert.equal(state.delivery.state,'PAUSED');});

test('developer provider availability classifier is narrow and requires no changed files',()=>{assert.equal(classifyProviderAvailability({stdout:"You've hit your session limit · resets 12am",changedFiles:[]}), 'provider_quota');assert.equal(classifyProviderAvailability({stderr:'Please run /login to continue',changedFiles:[]}), 'provider_auth');assert.equal(classifyProviderAvailability({stdout:'quota exceeded',changedFiles:['app.js']}),null);assert.equal(classifyProviderAvailability({stderr:'application auth assertion failed',changedFiles:[]}),null);assert.equal(classifyProviderAvailability({stderr:'spawn missing-agent ENOENT',changedFiles:[]}), 'provider_unavailable');assert.equal(classifyProviderAvailability({stdout:"I'm blocked on a permissions prompt; approve the file-write permission",changedFiles:[]}), 'provider_unavailable');assert.equal(classifyProviderAvailability({stdout:"I'm blocked on a permissions prompt",changedFiles:['app.js']}),null);assert.equal(classifyProviderAvailability({stdout:"Blocked by the session's read-only filesystem; no files were changed. Implementation requires a writable session.",changedFiles:[]}), 'provider_unavailable');assert.equal(classifyProviderAvailability({stdout:"The task context file is outside my sandboxed working directory. Path is outside allowed working directories.",changedFiles:[]}), 'provider_unavailable');assert.equal(classifyProviderAvailability({stdout:"The task context file is outside my sandboxed working directory. Path is outside allowed working directories.",changedFiles:['src/app.js']}), null);});

test('Claude print-mode developer accepts edits non-interactively without bypassing all permissions',()=>{const spec=commandForPrompt('claude','test prompt');assert.equal(spec.cmd,'claude');assert.deepEqual(spec.args.slice(0,5),['-p','--permission-mode','acceptEdits','--permission-prompts','none']);assert.equal(spec.args.at(-1),'test prompt');assert.equal(spec.args.includes('bypassPermissions'),false);assert.equal(spec.args.includes('--dangerously-skip-permissions'),false);});


test('Codex manager remains read-only while developer fallback gets workspace-write only',()=>{const manager=commandForPrompt('codex','manager prompt'),developer=commandFor('codex','/tmp/context.md');assert.equal(manager.cmd,'codex');assert.deepEqual(manager.args,['exec','manager prompt']);assert.equal(developer.cmd,'codex');assert.deepEqual(developer.args.slice(0,3),['exec','-s','workspace-write']);assert.equal(developer.args.includes('danger-full-access'),false);assert.equal(developer.args.includes('--dangerously-bypass-approvals-and-sandbox'),false);});


test('manager plan keeps only executable verification commands and supported evidence types',()=>{const state={tasks:[],profile:{}};const plan=normalizeManagerPlan({status:'PLAN',tasks:[{id:'T1',title:'Shell',acceptanceCriteria:['works'],verification:['npm test','Assert semantic controls and responsive contracts'],evidenceRequired:['test','diff','accepted integration evidence','governed supersession evidence']}]},state);const task=plan.tasks[0];assert.deepEqual(task.verification,['npm test']);assert.deepEqual(task.verificationNotes,['Assert semantic controls and responsive contracts']);assert.deepEqual(task.evidenceRequired,['test','diff']);assert.deepEqual(task.ignoredEvidenceRequirements,['accepted integration evidence','governed supersession evidence']);});

test('replacement lineage validates target and rewires dependents journal-safely',()=>{const root=tempRepo('replacement-links');initStore(root);addTasks([{id:'T01',title:'old',acceptanceCriteria:['old'],verification:['node --version'],allowedPaths:['src/**'],protectedPaths:[],evidenceRequired:['command'],dependsOn:[],priority:10,risk:'low',state:'PENDING'},{id:'T02',title:'dependent',acceptanceCriteria:['next'],verification:['node --version'],allowedPaths:['src/**'],protectedPaths:[],evidenceRequired:['command'],dependsOn:['T01'],priority:9,risk:'low',state:'PENDING'}],root);transition('T01','READY',{},root);transition('T01','RUNNING',{},root);transition('T01','FAILED',{},root);transition('T01','REJECTED',{},root);const raw={status:'PLAN',tasks:[{id:'T01R',title:'replacement',acceptanceCriteria:['fixed'],verification:['node --version'],evidenceRequired:['command','diff'],allowedPaths:['src/**'],dependsOn:[],replacesTaskId:'T01'}]};const normalized=normalizeManagerPlan(raw,readState(root));addTasks(normalized.tasks,root);applyReplacementLinks(normalized.tasks,root);let state=readState(root);assert.equal(state.tasks.find(t=>t.id==='T01').supersededBy,'T01R');assert.deepEqual(state.tasks.find(t=>t.id==='T02').dependsOn,['T01R']);state=replayStateFromJournal(root);assert.equal(state.tasks.find(t=>t.id==='T01').supersededBy,'T01R');assert.deepEqual(state.tasks.find(t=>t.id==='T02').dependsOn,['T01R']);assert.throws(()=>normalizeManagerPlan({status:'PLAN',tasks:[{id:'BAD',title:'bad',acceptanceCriteria:['bad'],replacesTaskId:'MISSING'}]},readState(root)),/replaces unknown task/);});
