import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import { tempRepo,writeTask,sh } from './helpers.js';import { initStore,addTasks,readState,transition } from '../src/store.js';import { loadTaskFiles } from '../src/spec.js';import { runTask } from '../src/runner.js';import { verifyTask } from '../src/verifier.js';import { acceptTask } from '../src/actions.js';
test('manual isolated lifecycle verifies evidence then explicitly integrates',async()=>{const root=tempRepo('life');initStore(root);const taskFile=writeTask(root);addTasks(loadTaskFiles(taskFile),root);sh(root,'git',['add','.gitignore','specs']);sh(root,'git',['commit','-m','shipstate control metadata']);const run=await runTask('TASK-001','manual',root);assert.equal(fs.readFileSync(path.join(root,'src/app.js'),'utf8').includes('hello shipstate'),false);fs.writeFileSync(path.join(run.worktreePath,'src/app.js'),'export const greeting = () => "hello shipstate";\n');const v=verifyTask('TASK-001',root);assert.equal(v.passed,true);assert.equal(readState(root).tasks[0].state,'VERIFIED');assert.equal(fs.readFileSync(path.join(root,'src/app.js'),'utf8').includes('hello shipstate'),false);const a=acceptTask('TASK-001',root);assert.equal(a.accepted,true);assert.equal(readState(root).tasks[0].state,'ACCEPTED');assert.equal(fs.readFileSync(path.join(root,'src/app.js'),'utf8').includes('hello shipstate'),true);});


test('retry execution clears stale blocked reason before implementation',async()=>{const root=tempRepo('retry-clears-block');initStore(root);const taskFile=writeTask(root);addTasks(loadTaskFiles(taskFile),root);sh(root,'git',['add','.gitignore','specs']);sh(root,'git',['commit','-m','shipstate control metadata']);transition('TASK-001','READY',{},root);transition('TASK-001','RUNNING',{},root);transition('TASK-001','FAILED',{blockedReason:'provider_quota',contextError:'old failure'},root);const run=await runTask('TASK-001','manual',root);const task=readState(root).tasks[0];assert.equal(run.status,'awaiting_manual');assert.equal(task.state,'IMPLEMENTED');assert.equal(task.blockedReason,null);assert.equal(task.contextError,null);});


test('operator can explicitly retry a rejected task without making rejected tasks auto-eligible',async()=>{const root=tempRepo('retry-rejected');initStore(root);const taskFile=writeTask(root);addTasks(loadTaskFiles(taskFile),root);sh(root,'git',['add','.gitignore','specs']);sh(root,'git',['commit','-m','shipstate control metadata']);transition('TASK-001','READY',{},root);transition('TASK-001','RUNNING',{},root);transition('TASK-001','FAILED',{},root);transition('TASK-001','REJECTED',{},root);const run=await runTask('TASK-001','manual',root);assert.equal(run.status,'awaiting_manual');assert.equal(readState(root).tasks[0].state,'IMPLEMENTED');});

test('non-manual local execution materializes context inside worktree and removes it before diff accounting',async()=>{const root=tempRepo('local-context-handoff');initStore(root);const taskFile=writeTask(root);addTasks(loadTaskFiles(taskFile),root);sh(root,'git',['add','.gitignore','specs']);sh(root,'git',['commit','-m','shipstate control metadata']);const run=await runTask('TASK-001','dry-run',root);assert.equal(run.status,'passed');assert.equal(run.changedFiles.includes('.shipstate-context.md'),false);assert.equal(fs.existsSync(path.join(run.worktreePath,'.shipstate-context.md')),false);assert.equal(readState(root).tasks[0].state,'IMPLEMENTED');});
