import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { tempRepo } from './helpers.js';
import { initStore,paths,readState } from '../src/store.js';
import { ensureProjectKit,readProjectContract,writeProjectContract,projectDocumentPath,REQUIRED_DOCUMENTS } from '../src/project-kit.js';
import { compileProjectTruth,readProjectTruth } from '../src/project-truth.js';

test('contract v1 is losslessly upgraded with v2 intelligence defaults',()=>{const root=tempRepo('contract-migration');initStore(root);ensureProjectKit(root);const legacy={schemaVersion:1,roles:{manager:'codex'},autonomy:{implementation:'automatic'},limits:{maxRepairCycles:2},delivery:{buildCommands:['npm test']},decisions:{product_scope:{status:'approved',note:'legacy'}}};fs.writeFileSync(`${root}/shipstate.project.json`,JSON.stringify(legacy,null,2));const c=readProjectContract(root);assert.equal(c.schemaVersion,2);assert.equal(c.roles.manager,'codex');assert.equal(c.decisions.product_scope.status,'approved');assert.equal(c.providers.structuralContext,'auto');assert.equal(c.qualityProfiles.accessibility,'required');assert.ok(Array.isArray(c.project.platforms));});

test('state v4 is transparently upgraded to v5 intelligence and repair projections',()=>{const root=tempRepo('state-migration');initStore(root);const p=paths(root),s=JSON.parse(fs.readFileSync(p.state,'utf8'));s.schemaVersion=4;delete s.intelligence;delete s.repairEpisodes;delete s.metrics.projectTruth;delete s.metrics.providers;delete s.metrics.tokenEconomy;fs.writeFileSync(p.state,JSON.stringify(s,null,2));const migrated=readState(root);assert.equal(migrated.schemaVersion,5);assert.deepEqual(migrated.repairEpisodes,[]);assert.deepEqual(migrated.intelligence.providers,{});assert.ok(Array.isArray(migrated.metrics.tokenEconomy));});

test('ProjectTruth invalidates when canonical source changes and preserves provenance',()=>{const root=tempRepo('truth-invalidation');initStore(root);ensureProjectKit(root);for(const d of REQUIRED_DOCUMENTS)fs.writeFileSync(projectDocumentPath(root,d),`# ${d.key}\n\n## Approved\n- Stable approved ${d.key} statement with enough detail to compile deterministically.\n`);const a=compileProjectTruth(root,{record:false});fs.appendFileSync(projectDocumentPath(root,REQUIRED_DOCUMENTS.find(x=>x.key==='features')),'\n- Newly approved offline synchronization requirement.\n');const b=readProjectTruth(root);assert.notEqual(a.contractHash,b.contractHash);assert.ok(b.requirements.some(x=>/offline synchronization/.test(x.statement)));assert.ok(b.requirements.every(x=>x.source.startsWith('docs/shipstate/FEATURES.md#')));});
