import fs from 'node:fs';
import path from 'node:path';
import { run,now,readJson } from '../utils.js';
import { readProjectContract } from '../project-kit.js';
import { withReadOnlyProviderRoot } from './isolation.js';

const BUILTINS=new Map(),MAX_RESULT_BYTES=2*1024*1024,ROI_WINDOW=30,HEALTH_TTL_MS=15000,HEALTH_CACHE=new Map();
function configSafe(root){try{return readProjectContract(root).providers||{};}catch{return {};}}
function safeResult(value,id){let text;try{text=JSON.stringify(value);}catch{throw new Error(`${id} provider returned a non-serializable result`);}if(Buffer.byteLength(text)>MAX_RESULT_BYTES)throw new Error(`${id} provider result exceeds ${MAX_RESULT_BYTES} bytes`);return value;}
function stateSafe(root){return readJson(path.join(root,'.shipstate','state.json'),{})||{};}
export function providerRoi(root=process.cwd(),id){const s=stateSafe(root),calls=(s.metrics?.providers||[]).filter(x=>x.provider===id).slice(-ROI_WINDOW),contexts=(s.metrics?.contexts||[]).filter(x=>x.provider===id).slice(-ROI_WINDOW),economy=(s.metrics?.tokenEconomy||[]).filter(x=>Object.values(x.providers||{}).includes(id)).slice(-ROI_WINDOW);if(!calls.length&&!contexts.length&&!economy.length)return {samples:0,successRate:null,averageLatencyMs:null,tokensAvoided:0,actualTokens:0,efficiencyRatio:0,adjustment:0};const failed=calls.filter(x=>x.available===false||x.passed===false).length,successRate=calls.length?(calls.length-failed)/calls.length:null,latencySamples=calls.length?calls.map(x=>Number(x.latencyMs||0)):economy.map(x=>Number(x.providerLatencyMs||0)),averageLatencyMs=latencySamples.length?Math.round(latencySamples.reduce((n,x)=>n+x,0)/latencySamples.length):null,tokensAvoided=contexts.length?contexts.reduce((n,x)=>n+Number(x.tokensAvoided||0),0):economy.reduce((n,x)=>n+Number(x.tokensAvoided||0),0),actualTokens=contexts.length?contexts.reduce((n,x)=>n+Number(x.tokens||0),0):economy.reduce((n,x)=>n+Number(x.actualTokens||0),0),efficiencyRatio=tokensAvoided/Math.max(1,actualTokens);let raw=0;if(contexts.length||economy.length)raw+=Math.min(35,Math.log2(1+Math.max(0,efficiencyRatio))*12);if(averageLatencyMs!==null)raw-=Math.min(35,averageLatencyMs/1000*2);if(successRate!==null)raw-=(1-successRate)*60;const samples=Math.max(calls.length,contexts.length,economy.length),confidence=Math.min(1,samples/5),adjustment=Math.round(raw*confidence);return {samples,calls:calls.length,contexts:contexts.length,economy:economy.length,successRate:successRate===null?null:Math.round(successRate*1000)/1000,averageLatencyMs,tokensAvoided,actualTokens,efficiencyRatio:Math.round(efficiencyRatio*1000)/1000,adjustment};}
export function registerProvider(provider){if(!provider?.id||!/^[a-z0-9][a-z0-9-]*$/i.test(provider.id))throw new Error('Provider id is required and must be identifier-safe');if(!Array.isArray(provider.capabilities)||!provider.capabilities.length)throw new Error(`Provider ${provider.id} must declare capabilities`);for(const fn of ['detect','query'])if(typeof provider[fn]!=='function')throw new Error(`Provider ${provider.id} must implement ${fn}()`);if(provider.readOnly===false)throw new Error(`Provider ${provider.id} must be read-only; state mutation belongs to SHIPSTATE`);BUILTINS.set(provider.id,Object.freeze({...provider,readOnly:true}));HEALTH_CACHE.clear();return provider;}
export function providerRegistry(){return new Map(BUILTINS);}
export function providersFor(capability){return [...BUILTINS.values()].filter(p=>p.capabilities.includes(capability));}
export function providerConfig(root=process.cwd()){return configSafe(root);}
function configuredId(capability,root){const p=configSafe(root),keys={structuralContext:'structural-context',semanticContext:'semantic-context',uiIntelligence:'ui-intelligence',discoverability:'discoverability'};for(const [key,cap] of Object.entries(keys))if(cap===capability)return p[key]||'auto';return 'auto';}
function detected(p,root,ctx){try{return p.detect(root,ctx);}catch(e){return {available:false,reason:e.message};}}
function rankOne(p,root,ctx){const detection=detected(p,root,ctx),base=Number(typeof p.score==='function'?p.score(root,ctx,detection):p.priority||0),roi=providerRoi(root,p.id);return {provider:p,detection,base,roi,total:base+roi.adjustment};}
function rankedProviders(capability,root,ctx){const wanted=configuredId(capability,root),all=providersFor(capability);if(wanted==='off')return [];let ranked=all.map(p=>rankOne(p,root,ctx)).filter(x=>x.detection?.available!==false).sort((a,b)=>b.total-a.total||a.provider.id.localeCompare(b.provider.id));if(wanted&&wanted!=='auto'){const exact=all.find(p=>p.id===wanted);if(!exact)throw new Error(`Configured provider ${wanted} does not support ${capability}`);const selected=rankOne(exact,root,ctx);if(selected.detection?.available===false)throw new Error(`Configured provider ${wanted} is unavailable: ${selected.detection?.reason||'detection failed'}`);ranked=[selected,...ranked.filter(x=>x.provider.id!==wanted)];}return ranked;}
export function clearProviderHealthCache(root=null){if(root===null)HEALTH_CACHE.clear();else HEALTH_CACHE.delete(path.resolve(root));}
export function providerHealth(root=process.cwd(),{refresh=false}={}){const key=path.resolve(root),cached=HEALTH_CACHE.get(key),t=Date.now();if(!refresh&&cached&&t-cached.at<HEALTH_TTL_MS)return structuredClone(cached.value);const value=[...BUILTINS.values()].map(p=>({id:p.id,capabilities:p.capabilities,network:Boolean(p.network),readOnly:true,roi:providerRoi(root,p.id),detected:detected(p,root,{})}));HEALTH_CACHE.set(key,{at:t,value});return structuredClone(value);}
export function chooseProvider(capability,root=process.cwd(),ctx={}){return rankedProviders(capability,root,ctx)[0]?.provider||null;}
export async function queryProvider(capability,input,root=process.cwd(),ctx={}){const started=Date.now(),ranked=rankedProviders(capability,root,ctx),attempts=[];for(const choice of ranked){const provider=choice.provider,t=Date.now();try{const isolated=await withReadOnlyProviderRoot(root,provider.id,async(providerRoot,isolation)=>{const providerCtx={...ctx,...isolation};if(typeof provider.prepare==='function'&&ctx.prepare!==false)await provider.prepare(providerRoot,providerCtx);return {result:await provider.query(input,providerRoot,providerCtx),isolation};});const result=safeResult(isolated.result,provider.id),providerLatencyMs=Date.now()-t;return {provider:provider.id,available:true,result,latencyMs:Date.now()-started,providerLatencyMs,isolation:isolated.isolation.isolation,selection:{baseScore:choice.base,roiAdjustment:choice.roi.adjustment,totalScore:choice.total,roi:choice.roi},attempts,at:now(),fallbackFrom:attempts.map(x=>x.provider)};}catch(e){attempts.push({provider:provider.id,error:String(e.message||e).slice(0,1000),latencyMs:Date.now()-t,score:choice.total});}}return {provider:ranked[0]?.provider.id||null,available:false,error:attempts.at(-1)?.error||'no provider available',result:null,latencyMs:Date.now()-started,attempts,at:now()};}
export function executableOnPath(name){return run(process.platform==='win32'?'where':'which',[name],{timeout:5000,maxBuffer:1024*1024}).status===0;}
export function providerDataDir(root=process.cwd(),id='provider'){const p=path.join(root,'.shipstate','providers',id);fs.mkdirSync(p,{recursive:true});return p;}
