import fs from 'node:fs';import path from 'node:path';import { paths,readState,recordMetric } from './store.js';import { sha256,estimateTokens,walk,unique } from './utils.js';import { gitHistory } from './git.js';import { callIntegration } from './integrations.js';
const IGNORE=['.git/**','.shipstate/**','node_modules/**','vendor/**','dist/**','build/**','.next/**','coverage/**'];
function read(root,rel,max=12000){try{return fs.readFileSync(path.join(root,rel),'utf8').slice(0,max);}catch{return '';}}
function importsFor(file,text){const out=[];const ext=path.extname(file);
 if(['.js','.jsx','.ts','.tsx','.mjs','.cjs'].includes(ext)){for(const m of text.matchAll(/(?:from\s+|require\s*\(|import\s*\()?["']([^"']+)["']/g))if(m[1]?.startsWith('.'))out.push(m[1]);}
 else if(ext==='.py'){for(const m of text.matchAll(/^\s*(?:from\s+([\w.]+)|import\s+([\w.]+))/gm))out.push((m[1]||m[2]||'').replaceAll('.','/'));}
 else if(ext==='.go'){for(const m of text.matchAll(/["`]([^"`]+)["`]/g))if(m[1]&&!m[1].includes(' '))out.push(m[1]);}
 else if(ext==='.rs'){for(const m of text.matchAll(/^\s*(?:use|mod)\s+([\w:]+)/gm))out.push(m[1].replaceAll('::','/'));}
 else if(['.java','.kt','.kts'].includes(ext)){for(const m of text.matchAll(/^\s*import\s+([\w.]+)/gm))out.push(m[1].replaceAll('.','/'));}
 return unique(out);
}
function symbols(text){const out=[];for(const re of [/\b(?:function|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)/g,/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*[=:]/g,/^\s*(?:def|class)\s+([A-Za-z_]\w*)/gm,/\bfunc\s+(?:\([^)]*\)\s*)?([A-Za-z_]\w*)/g])for(const m of text.matchAll(re))out.push(m[1]);return unique(out).slice(0,100);}
function resolveImport(root,from,imp,all){if(!imp.startsWith('.'))return null;const base=path.posix.normalize(path.posix.join(path.posix.dirname(from),imp));const candidates=[base,`${base}.ts`,`${base}.tsx`,`${base}.js`,`${base}.jsx`,`${base}.py`,`${base}/index.ts`,`${base}/index.js`];return candidates.find(c=>all.has(c))||null;}
export function buildRepositoryIndex(root=process.cwd()){
 const files=walk(root,{ignore:IGNORE}).filter(f=>!f.includes('\0'));const set=new Set(files);const index={files:{},symbols:{},reverseImports:{}};
 for(const f of files){let text='';try{const st=fs.statSync(path.join(root,f));if(st.size>300000)continue;text=fs.readFileSync(path.join(root,f),'utf8');}catch{continue;}const imps=importsFor(f,text);const resolved=imps.map(i=>resolveImport(root,f,i,set)).filter(Boolean);const syms=symbols(text);index.files[f]={imports:resolved,symbols:syms,size:Buffer.byteLength(text)};for(const s of syms)(index.symbols[s]||=[]).push(f);for(const r of resolved)(index.reverseImports[r]||=[]).push(f);}
 return index;
}
function lexicalScore(file,task){const hay=`${file} ${task.title} ${task.objective} ${(task.acceptanceCriteria||[]).join(' ')}`.toLowerCase();const words=unique(`${task.title} ${task.objective}`.toLowerCase().match(/[a-z][a-z0-9_-]{2,}/g)||[]).filter(w=>!['the','and','for','with','from','this','that','task'].includes(w));return words.reduce((n,w)=>n+(hay.includes(w)?1:0),0);}
export function selectContextFiles(task,root,index,budgetTokens=12000){const all=Object.keys(index.files);const picked=[];const add=f=>{if(f&&index.files[f]&&!picked.includes(f))picked.push(f);};for(const f of task.files||[])add(f);
 const ranked=all.map(f=>[f,lexicalScore(f,task)]).filter(([,s])=>s>0).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([f])=>f);ranked.forEach(add);
 for(const f of [...picked]){for(const d of index.files[f]?.imports||[])add(d);for(const r of index.reverseImports[f]||[])add(r);const base=path.basename(f).replace(/\.(tsx?|jsx?|py|go|rs|java|kt)$/,'');for(const cand of all)if((cand.includes('/test')||/\.(test|spec)\./.test(cand))&&cand.toLowerCase().includes(base.toLowerCase()))add(cand);}
 let tokens=0;const selected=[];for(const f of picked){const content=read(root,f);const t=estimateTokens(content);if(selected.length&&tokens+t>budgetTokens)continue;selected.push({file:f,content,tokens:t,symbols:index.files[f]?.symbols||[]});tokens+=t;}return {selected,tokens};}
function priorRuns(taskId,s){return s.runs.filter(r=>r.taskId===taskId).slice(-5);}
export function compileContext(taskId,root=process.cwd(),opts={}){const s=readState(root);const task=s.tasks.find(t=>t.id===taskId);if(!task)throw new Error(`Unknown task: ${taskId}`);const semantic=callIntegration('codeAtlas','context',{taskId,task},root,{optional:true});const taskForContext=semantic?.files?.length?{...task,files:[...(task.files||[]),...semantic.files]}:task;const index=buildRepositoryIndex(root);const budget=Number(opts.budgetTokens||s.project.contextBudgetTokens||12000);const sel=selectContextFiles(taskForContext,root,index,budget);const chunks=[`# SHIPSTATE Execution Context`,`## Task\n${task.id}: ${task.title}`,`## Objective\n${task.objective||task.title}`];
 if(task.acceptanceCriteria?.length)chunks.push(`## Acceptance Criteria\n${task.acceptanceCriteria.map(x=>`- ${x}`).join('\n')}`);if(task.managerBrief)chunks.push(`## Codex Manager Brief\n${task.managerBrief}`);if(task.managerImplementationNotes?.length)chunks.push(`## Manager Implementation Notes\n${task.managerImplementationNotes.map(x=>`- ${x}`).join('\n')}`);if(task.verificationFocus?.length)chunks.push(`## Manager Verification Focus\n${task.verificationFocus.map(x=>`- ${x}`).join('\n')}`);if(task.reviewFeedback)chunks.push(`## Required Repair / Review Feedback\n${task.reviewFeedback}`);if(task.reviewFindings?.length)chunks.push(`## Reviewer Findings\n${task.reviewFindings.map(x=>`- [${x.severity||'normal'}] ${x.file||''} ${x.issue||JSON.stringify(x)}`).join('\n')}`);
 if(task.dependsOn?.length)chunks.push(`## Accepted Dependencies\n${task.dependsOn.map(x=>`- ${x}`).join('\n')}`);if(s.locks?.length)chunks.push(`## Design Locks\n${s.locks.map(l=>`- [${l.severity||'normal'}] ${l.id}: ${l.statement}`).join('\n')}`);
 chunks.push(`## Project Profile\n${JSON.stringify({ecosystems:s.profile?.ecosystems,languages:s.profile?.languages,frameworks:s.profile?.frameworks,commands:s.profile?.commands},null,2)}`);
 const pr=priorRuns(taskId,s);if(semantic?.notes)chunks.push(`## CodeAtlas Context Provider\n${semantic.notes}`);if(pr.length)chunks.push(`## Previous Attempts\n${pr.map(r=>`- ${r.id} ${r.agent} ${r.status}${r.failureFingerprint?` fingerprint:${r.failureFingerprint}`:''}`).join('\n')}`);
 const hist=gitHistory(root,sel.selected.map(x=>x.file),8);if(hist.length)chunks.push(`## Relevant Git History\n${hist.map(x=>`- ${x}`).join('\n')}`);
 chunks.push(`## Repository Context`);for(const x of sel.selected)chunks.push(`### ${x.file}\nSymbols: ${(x.symbols||[]).join(', ')||'n/a'}\n\`\`\`\n${x.content}\n\`\`\``);
 chunks.push(`## Execution Constraints\n- Implement only this bounded task.\n- Stay within allowed paths.\n- Never edit .git, .shipstate, shipstate.project.json, docs/shipstate, or .env files.\n- Do not redefine approved product scope, design, architecture, security, cost or deployment decisions.\n- If review feedback exists, resolve it completely.\n- Do not claim VERIFIED, APPROVED, ACCEPTED or DELIVERED; SHIPSTATE and the reviewer own those transitions.`);
 const text=chunks.join('\n\n');const p=paths(root);fs.mkdirSync(p.contexts,{recursive:true});const out=path.join(p.contexts,`${taskId}.md`);fs.writeFileSync(out,text);const metric={at:new Date().toISOString(),taskId,bytes:Buffer.byteLength(text),tokens:estimateTokens(text),repositoryFiles:Object.keys(index.files).length,repositoryBytes:Object.values(index.files).reduce((a,x)=>a+(x.size||0),0),selectedFiles:sel.selected.map(x=>x.file),selectedFileCount:sel.selected.length,budgetTokens:budget,hash:sha256(text)};recordMetric('contexts',metric,root);return {path:out,text,hash:metric.hash,bytes:metric.bytes,tokens:metric.tokens,files:metric.selectedFiles,index};}
