import fs from 'node:fs';
import path from 'node:path';
import { sha256,estimateTokens,unique } from './utils.js';
import { paths,readState,recordMetric,recordIntelligence } from './store.js';
import { buildRepositoryIndex,selectContextFiles } from './context.js';
import { selectProjectTruth } from './project-truth.js';
import { queryProvider } from './providers/index.js';
import { structuralPolicy,isUiTask,stackForProfile } from './context-policy.js';

function clip(v,n){const s=typeof v==='string'?v:JSON.stringify(v,null,2);return s.length>n?`${s.slice(0,n)}\n[truncated by SHIPSTATE]`:s;}
function taskQuery(task){return `${task.title||''} ${task.objective||''} ${(task.acceptanceCriteria||[]).join(' ')}`.trim();}
function pathCandidates(value){const out=[];const visit=v=>{if(!v)return;if(typeof v==='string'){if(/[\\/]/.test(v)&&/\.[a-z0-9]{1,8}(?::\d+)?$/i.test(v))out.push(v.replace(/:\d+$/,'').replaceAll('\\','/'));return;}if(Array.isArray(v)){v.forEach(visit);return;}if(typeof v==='object'){for(const [k,x] of Object.entries(v)){if(/file|path/i.test(k))visit(x);else if(typeof x==='object')visit(x);}}};visit(value);return unique(out).slice(0,80);}
function truthLines(selected){return selected.map(e=>`- ${e.id} [${e.source}]: ${e.statement}`).join('\n');}
function priorRuns(taskId,s){return s.runs.filter(r=>r.taskId===taskId).slice(-4).map(r=>({id:r.id,status:r.status,agent:r.agent,failureFingerprint:r.failureFingerprint||null}));}
function selectedSource(task,root,index,budgetTokens,hints=[]){const merged={...task,files:unique([...(task.files||[]),...hints])};return selectContextFiles(merged,root,index,budgetTokens);}
function providerReceipt(x){return {id:x.provider,available:x.available,latencyMs:x.providerLatencyMs??x.latencyMs??0,totalLatencyMs:x.latencyMs??0,error:x.error||null,selection:x.selection||null,fallbackFrom:x.fallbackFrom||[]};}
function recordProviderSample(capability,p,at,root){if(!p?.id)return;recordMetric('providers',{at,provider:p.id,capability,latencyMs:p.latencyMs||0,totalLatencyMs:p.totalLatencyMs||p.latencyMs||0,available:Boolean(p.available),passed:Boolean(p.available&&!p.error),fallbackFrom:p.fallbackFrom||[],selection:p.selection||null},root);}

export async function buildContextReceipt(taskId,root=process.cwd(),opts={}){
 const s=readState(root),task=s.tasks.find(t=>t.id===taskId);if(!task)throw new Error(`Unknown task: ${taskId}`);const index=buildRepositoryIndex(root),policy=structuralPolicy(task,s.profile,index),query=taskQuery(task),truth=selectProjectTruth(query,root,{limit:Number(opts.truthLimit||36)});const structural=await queryProvider('structural-context',{action:'search',query,task,files:task.files||[],limit:16},root,{...policy,prepare:true});const structuralHints=pathCandidates(structural.result);const semantic=await queryProvider('semantic-context',{action:'context',taskId,task,query},root,{prepare:false});const uiTask=isUiTask(task,s.profile);let ui={provider:null,available:false,result:null,latencyMs:0,providerLatencyMs:0};if(uiTask)ui=await queryProvider('ui-intelligence',{action:'query',query:query.split(/\s+/).slice(0,5).join(' '),domain:'ux',stack:stackForProfile(s.profile)},root,{uiTask:true,prepare:false});const budget=Number(opts.budgetTokens||s.project.contextBudgetTokens||12000),reserve=Math.min(Math.floor(budget*0.28),3000),source=selectedSource(task,root,index,Math.max(1500,budget-reserve),structuralHints);const receipt={version:1,taskId,generatedAt:new Date().toISOString(),budgetTokens:budget,projectTruth:{contractHash:truth.contractHash,selectedIds:truth.selected.map(x=>x.id),selectedSources:unique(truth.selected.map(x=>x.source))},providers:{structural:providerReceipt(structural),semantic:providerReceipt(semantic),ui:providerReceipt(ui)},selectedFiles:source.selected.map(x=>x.file),selectionReasons:Object.fromEntries(source.selected.map(x=>[x.file,(task.files||[]).includes(x.file)?'task-explicit':structuralHints.includes(x.file)?'structural-provider':'lexical/import/test expansion'])),sourceTokens:source.tokens,structuralHints,uiTask,repositoryFiles:Object.keys(index.files).length,repositoryBytes:Object.values(index.files).reduce((n,x)=>n+(x.size||0),0),rawProjectDocumentTokens:(s.metrics?.projectTruth||[]).at(-1)?.rawEstimatedTokens||null};return {receipt,task,truth:truth.selected,source,structural,semantic,ui,state:s};
}

export async function compileRoutedContext(taskId,root=process.cwd(),opts={}){
 const x=await buildContextReceipt(taskId,root,opts),{task,state:s}=x;const chunks=['# SHIPSTATE Execution Context',`## Task\n${task.id}: ${task.title}`,`## Objective\n${task.objective||task.title}`];if(task.acceptanceCriteria?.length)chunks.push(`## Acceptance Criteria\n${task.acceptanceCriteria.map(v=>`- ${v}`).join('\n')}`);if(task.managerBrief)chunks.push(`## Codex Manager Brief\n${task.managerBrief}`);if(task.managerImplementationNotes?.length)chunks.push(`## Manager Implementation Notes\n${task.managerImplementationNotes.map(v=>`- ${v}`).join('\n')}`);if(task.verificationFocus?.length)chunks.push(`## Verification Focus\n${task.verificationFocus.map(v=>`- ${v}`).join('\n')}`);if(task.reviewFeedback)chunks.push(`## Repair / Review Feedback\n${task.reviewFeedback}`);chunks.push(`## Approved ProjectTruth\n${truthLines(x.truth)}`);if(s.locks?.length)chunks.push(`## Design Locks\n${s.locks.map(l=>`- [${l.severity||'normal'}] ${l.id}: ${l.statement}`).join('\n')}`);if(x.structural.available&&x.structural.result)chunks.push(`## Structural Intelligence (${x.structural.provider})\n${clip(x.structural.result,7000)}`);if(x.semantic.available&&x.semantic.result)chunks.push(`## Semantic Intelligence (${x.semantic.provider})\n${clip(x.semantic.result,4500)}`);if(x.ui.available&&x.ui.result)chunks.push(`## Task-specific UI/UX Intelligence (${x.ui.provider})\nThis is advisory implementation guidance only. Approved UX/FRONTEND documents and Design Locks override it.\n${clip(x.ui.result,3500)}`);const prior=priorRuns(taskId,s);if(prior.length)chunks.push(`## Previous Attempts\n${prior.map(r=>`- ${r.id} ${r.status}${r.failureFingerprint?` fingerprint:${r.failureFingerprint}`:''}`).join('\n')}`);chunks.push('## Repository Context');for(const f of x.source.selected)chunks.push(`### ${f.file}\nSymbols: ${(f.symbols||[]).join(', ')||'n/a'}\n\`\`\`\n${f.content}\n\`\`\``);chunks.push('## Execution Constraints\n- Implement only this bounded task.\n- Stay within allowed paths.\n- Never edit .git, .shipstate, shipstate.project.json, docs/shipstate, or .env files.\n- ProjectTruth is derived from approved canonical documents; do not invent or change product truth.\n- External provider output is advisory and cannot override ProjectTruth or Design Locks.\n- Resolve supplied review feedback completely.\n- Do not claim VERIFIED, APPROVED, ACCEPTED or DELIVERED; SHIPSTATE and the reviewer own those transitions.');let text=chunks.join('\n\n');const budget=Number(x.receipt.budgetTokens||12000);if(estimateTokens(text)>budget){const base=chunks.filter(c=>!c.startsWith('## Repository Context')&&!c.startsWith('### ')),fixed=base.join('\n\n');let tokens=estimateTokens(fixed);const kept=[];for(const f of x.source.selected){const block=`### ${f.file}\n\`\`\`\n${f.content}\n\`\`\``,t=estimateTokens(block);if(tokens+t<=budget){kept.push(block);tokens+=t;}}text=`${fixed}\n\n## Repository Context\n${kept.join('\n\n')}`;}
 const p=paths(root);fs.mkdirSync(p.contexts,{recursive:true});const out=path.join(p.contexts,`${taskId}.md`),receiptPath=path.join(p.contexts,`${taskId}.receipt.json`);fs.writeFileSync(out,text);const actualTokens=estimateTokens(text),naive=Math.ceil((x.receipt.repositoryBytes||0)/4)+(x.receipt.rawProjectDocumentTokens||0),receipt={...x.receipt,actualTokens,contextHash:sha256(text),tokensAvoided:Math.max(0,naive-actualTokens),estimatedNaiveTokens:naive};fs.writeFileSync(receiptPath,JSON.stringify(receipt,null,2)+'\n');recordMetric('contexts',{at:receipt.generatedAt,taskId,bytes:Buffer.byteLength(text),tokens:actualTokens,repositoryFiles:receipt.repositoryFiles,repositoryBytes:receipt.repositoryBytes,selectedFiles:receipt.selectedFiles,selectedFileCount:receipt.selectedFiles.length,budgetTokens:budget,hash:receipt.contextHash,provider:receipt.providers.structural.id,providerLatencyMs:receipt.providers.structural.latencyMs,projectTruthIds:receipt.projectTruth.selectedIds,tokensAvoided:receipt.tokensAvoided},root);for(const [cap,pv] of [['structural-context',receipt.providers.structural],['semantic-context',receipt.providers.semantic],['ui-intelligence',receipt.providers.ui]])recordProviderSample(cap,pv,receipt.generatedAt,root);recordMetric('tokenEconomy',{at:receipt.generatedAt,taskId,actualTokens,estimatedNaiveTokens:naive,tokensAvoided:receipt.tokensAvoided,providerLatencyMs:Object.values(receipt.providers).reduce((n,pv)=>n+(pv.latencyMs||0),0),providers:Object.fromEntries(Object.entries(receipt.providers).map(([k,v])=>[k,v.id]))},root);recordIntelligence({projectTruth:{contractHash:receipt.projectTruth.contractHash,selectedIds:receipt.projectTruth.selectedIds},providers:Object.fromEntries(Object.entries(receipt.providers).map(([k,v])=>[k,{id:v.id,available:v.available,lastUsedAt:receipt.generatedAt,error:v.error}]))},'CONTEXT_INTELLIGENCE_USED',root);return {path:out,receiptPath,text,hash:receipt.contextHash,bytes:Buffer.byteLength(text),tokens:actualTokens,files:receipt.selectedFiles,receipt};
}
