import { id,now,runShell } from './utils.js';
import { readState,writeState,appendEvent,addTasks,addPlan,mutateTask,recordDecision,recordEvidence,refreshProfile } from './store.js';
import { chooseNext } from './core.js';
import { runTask } from './runner.js';
import { verifyTask } from './verifier.js';
import { acceptTask,rejectTask } from './actions.js';
import { readProjectContract,CONTROL_PATHS } from './project-kit.js';
import { assertHandoverCurrent,setProjectLifecycle,addOwnerDecision } from './handover.js';
import { managerPreflight,managerPlan,managerTaskBrief,reviewerDecision,managerCompletion } from './agent-team.js';

const ACTIVE=new Map();
export function activeDeliveries(){return [...ACTIVE.entries()].map(([root,x])=>({root,sessionId:x.sessionId,startedAt:x.startedAt}));}
export function isDeliveryActive(root=process.cwd()){return ACTIVE.has(root);}
function openDecisions(root){return (readState(root).ownerDecisions||[]).filter(x=>x.status==='OPEN');}
function createAiDecisions(items,source,root,taskId=null){return (items||[]).map(d=>addOwnerDecision({...d,source,taskId},root));}
function normalizeId(value,fallback){return String(value||fallback).toUpperCase().replace(/[^A-Z0-9._-]/g,'-');}
function normalizeTask(raw,index){const idValue=normalizeId(raw.id,`AI-${String(index+1).padStart(3,'0')}`);const risk=['low','medium','high'].includes(String(raw.risk||'').toLowerCase())?String(raw.risk).toLowerCase():'medium';return {id:idValue,title:String(raw.title||idValue).slice(0,140),objective:String(raw.objective||raw.title||idValue).slice(0,3000),acceptanceCriteria:(raw.acceptanceCriteria||[]).map(String).filter(Boolean).slice(0,30),verification:(raw.verification||[]).map(String).filter(Boolean).slice(0,20),files:(raw.files||[]).map(String).filter(Boolean).slice(0,50),allowedPaths:(raw.allowedPaths||[]).map(String).filter(Boolean).filter(x=>!CONTROL_PATHS.includes(x)).slice(0,50),protectedPaths:[...new Set([...(raw.protectedPaths||[]).map(String),...CONTROL_PATHS])],evidenceRequired:(raw.evidenceRequired||['command','diff']).map(String).filter(Boolean).slice(0,20),dependsOn:(raw.dependsOn||[]).map(x=>normalizeId(x,x)).filter(Boolean),priority:Number.isFinite(Number(raw.priority))?Number(raw.priority):50,risk,milestone:raw.milestone||null,state:'PENDING',createdAt:now(),updatedAt:now(),source:'codex-manager'};}
function assertTaskGraph(tasks,existingIds){const all=new Set([...existingIds,...tasks.map(t=>t.id)]);for(const t of tasks)for(const d of t.dependsOn)if(!all.has(d))throw new Error(`Manager task ${t.id} depends on unknown task ${d}`);const by=Object.fromEntries(tasks.map(t=>[t.id,t]));const visiting=new Set(),done=new Set();const visit=id=>{if(done.has(id)||!by[id])return;if(visiting.has(id))throw new Error(`Manager task graph contains cycle at ${id}`);visiting.add(id);for(const d of by[id].dependsOn)visit(d);visiting.delete(id);done.add(id);};for(const t of tasks)visit(t.id);}
export function normalizeManagerPlan(result,state){
  if(result?.status==='OWNER_DECISION_REQUIRED')return {status:result.status,decisions:result.decisions||[]};if(result?.status!=='PLAN'&&result?.verdict!=='ADD_TASKS')throw new Error(`Manager returned unsupported plan status: ${result?.status||result?.verdict||'missing'}`);const existing=new Set(state.tasks.map(t=>t.id)),generated=new Set(),tasks=[];for(const [i,raw] of (result.tasks||[]).slice(0,80).entries()){const t=normalizeTask(raw,i);if(existing.has(t.id))continue;if(generated.has(t.id))throw new Error(`Manager returned duplicate task id: ${t.id}`);generated.add(t.id);tasks.push(t);}assertTaskGraph(tasks,existing);for(const t of tasks){if(!t.acceptanceCriteria.length)throw new Error(`Manager task ${t.id} has no acceptance criteria`);if(t.dependsOn.includes(t.id))throw new Error(`Manager task ${t.id} cannot depend on itself`);}return {status:'PLAN',summary:result.summary||'',milestones:result.milestones||[],tasks};
}
function applyManagerPlan(result,root){const s=readState(root),normalized=normalizeManagerPlan(result,s);if(normalized.status==='OWNER_DECISION_REQUIRED'){createAiDecisions(normalized.decisions,'codex-manager-plan',root);return normalized;}if(!normalized.tasks.length)return normalized;const plan={id:id('ai-plan'),createdAt:now(),approvedAt:now(),status:'APPROVED_AUTONOMOUS',source:'codex-manager',summary:normalized.summary,milestones:normalized.milestones,tasks:normalized.tasks};addPlan(plan,root);addTasks(normalized.tasks,root);recordDecision({id:id('decision'),type:'autonomous-plan',actor:'codex',at:now(),planId:plan.id,taskCount:normalized.tasks.length},root);return normalized;}
function setHandoverActive(root){const s=readState(root);s.handover={...(s.handover||{}),status:'HANDED_OVER',handedOverAt:s.handover?.handedOverAt||now()};appendEvent('PROJECT_HANDED_OVER',{contractHash:s.handover.contractHash},root);writeState(s,root);}
function pauseForAgentDecision(result,source,root,taskId=null){const items=result?.decisions?.length?result.decisions:[{title:'AI team needs owner decision',question:result?.summary||'A material project decision is required before autonomous development can continue.',options:[],recommendation:null,impact:'Only the affected autonomous path is paused.'}];createAiDecisions(items,source,root,taskId);return {paused:true,reason:'owner-decision'};}
function markDelivery(patch,root){const s=readState(root);s.delivery={...(s.delivery||{}),...patch};writeState(s,root);return s.delivery;}

function certificationCommands(state,contract){return [...new Set([...(state.profile?.commands?.test?[state.profile.commands.test]:[]),...(state.profile?.commands?.typecheck?[state.profile.commands.typecheck]:[]),...(state.profile?.commands?.lint?[state.profile.commands.lint]:[]),...(state.profile?.commands?.build?[state.profile.commands.build]:[]),...(contract.delivery?.buildCommands||[])].filter(Boolean))];}
export function certifyProject(root=process.cwd()){
  refreshProfile(root);const s=readState(root),contract=readProjectContract(root);const notAccepted=s.tasks.filter(t=>t.state!=='ACCEPTED');if(notAccepted.length)return {passed:false,reason:`${notAccepted.length} tasks are not ACCEPTED`,tasks:notAccepted.map(t=>({id:t.id,state:t.state}))};const commands=certificationCommands(s,contract);if(!commands.length)return {passed:false,reason:'No deterministic project certification commands were detected or configured'};const evidence=[];let passed=true;for(const command of commands){const r=runShell(command,root,process.env,30*60*1000);const ev={id:id('ev'),taskId:'PROJECT',type:'project-certification',source:command,status:r.status===0?'passed':'failed',exitCode:r.status??1,stdout:(r.stdout||'').slice(-8000),stderr:(r.stderr||'').slice(-8000),createdAt:now()};evidence.push(ev);if(r.status!==0)passed=false;}recordEvidence(evidence,root);return {passed,evidence};
}
function runDeliveryCommands(commands,type,root){const evidence=[];let passed=true;for(const command of commands||[]){const r=runShell(command,root,process.env,45*60*1000);const ev={id:id('ev'),taskId:'PROJECT',type,source:command,status:r.status===0?'passed':'failed',exitCode:r.status??1,stdout:(r.stdout||'').slice(-8000),stderr:(r.stderr||'').slice(-8000),createdAt:now()};evidence.push(ev);if(r.status!==0){passed=false;break;}}if(evidence.length)recordEvidence(evidence,root);return {passed,evidence};}
function gateAuthorized(gate,state){return Boolean(state.delivery?.authorizedGates?.[gate]);}
function requireGate(gate,title,question,root){const existing=(readState(root).ownerDecisions||[]).find(d=>d.status==='OPEN'&&d.gate===gate);if(existing)return existing;return addOwnerDecision({gate,title,question,options:['approve','pause'],recommendation:'approve',impact:`${gate} waits for explicit owner authorization.`,source:'shipstate-gate'},root);}
function rollbackIfConfigured(contract,root){return (contract.delivery?.rollbackCommands||[]).length?runDeliveryCommands(contract.delivery.rollbackCommands,'rollback',root):null;}
function deployAndValidate(contract,root){setProjectLifecycle('DEPLOYMENT',{},root);const deployed=runDeliveryCommands(contract.delivery?.deployCommands,'deployment',root);if(!deployed.passed){setProjectLifecycle('BLOCKED',{lastError:'deployment failed'},root);return {passed:false,deployment:deployed};}setProjectLifecycle('DELIVERY_VALIDATION',{},root);const smoke=runDeliveryCommands(contract.delivery?.smokeCommands,'production-smoke',root);if(!smoke.passed){const rollback=rollbackIfConfigured(contract,root);setProjectLifecycle('BLOCKED',{lastError:'production smoke failed',rollbackAttempted:Boolean(rollback)},root);return {passed:false,deployment:deployed,smoke,rollback};}return {passed:true,deployment:deployed,smoke};}
async function finishProject(root){
  setProjectLifecycle('INTERNAL_CERTIFICATION',{},root);const cert=certifyProject(root);if(!cert.passed){setProjectLifecycle('FAILED_CERTIFICATION',{lastError:cert.reason||'project certification failed'},root);return {complete:false,certification:cert};}setProjectLifecycle('RELEASE_CANDIDATE',{},root);const contract=readProjectContract(root);let state=readState(root);if(contract.autonomy?.release==='owner_gate'&&!gateAuthorized('release',state)){requireGate('release','Release approval required','SHIPSTATE certification passed. Approve release/deployment continuation?',root);return {complete:false,awaiting:'release'};}
  state=readState(root);const deploymentMode=contract.autonomy?.deployment;if(deploymentMode==='owner_gate'&&!gateAuthorized('deployment',state)){requireGate('deployment','Deployment approval required','The certified release candidate is ready. Approve deployment?',root);return {complete:false,awaiting:'deployment'};}
  const shouldDeploy=deploymentMode==='automatic'||deploymentMode==='owner_gate'&&gateAuthorized('deployment',readState(root));let deliveryEvidence=null;if(shouldDeploy&&(contract.delivery?.deployCommands||[]).length){deliveryEvidence=deployAndValidate(contract,root);if(!deliveryEvidence.passed)return {complete:false,certification:cert,...deliveryEvidence};}
  setProjectLifecycle('DELIVERY_READY',{deployed:Boolean(deliveryEvidence?.passed)},root);if(contract.autonomy?.release==='automatic'||gateAuthorized('release',readState(root))){setProjectLifecycle('DELIVERED',{deployed:Boolean(deliveryEvidence?.passed)},root);return {complete:true,delivered:true,certification:cert,...(deliveryEvidence||{})};}return {complete:true,deliveryReady:true,certification:cert,...(deliveryEvidence||{})};
}

export async function runAutonomousDelivery(options={},root=process.cwd()){
  assertHandoverCurrent(root);if(openDecisions(root).length){setProjectLifecycle('OWNER_DECISION_REQUIRED',{waitingOnDecisionId:openDecisions(root)[0].id},root);return {paused:true,reason:'open-owner-decision'};}const contract=readProjectContract(root),roles={...contract.roles,...Object.fromEntries(Object.entries(options.roles||{}).filter(([,v])=>Boolean(v)))};const sessionId=id('delivery');const maxTasks=Number(options.maxTasks||contract.limits?.maxTasksPerSession||100),maxRepairs=Number(options.maxRepairs||contract.limits?.maxRepairCycles||3);let processed=0;const outcomes=[];
  let state=readState(root);if(!state.delivery?.preflightPassed){setProjectLifecycle('HANDOVER_REVIEW',{sessionId},root);const preflight=await managerPreflight(root,roles.manager);if(preflight.status!=='READY')return pauseForAgentDecision(preflight,'codex-preflight',root);markDelivery({preflightPassed:true,preflightPassedAt:now()},root);}setHandoverActive(root);setProjectLifecycle('AUTONOMOUS_DEVELOPMENT',{sessionId,pauseReason:null,waitingOnDecisionId:null},root);
  state=readState(root);if(state.delivery?.forceReplan){const replanned=await managerPlan(root,roles.manager);if(replanned.status==='OWNER_DECISION_REQUIRED')return pauseForAgentDecision(replanned,'codex-owner-replan',root);applyManagerPlan(replanned,root);markDelivery({forceReplan:false,planBootstrapped:true,lastReplannedAt:now()},root);}else if(!state.delivery?.planBootstrapped){const planResult=await managerPlan(root,roles.manager);if(planResult.status==='OWNER_DECISION_REQUIRED')return pauseForAgentDecision(planResult,'codex-manager-plan',root);applyManagerPlan(planResult,root);markDelivery({planBootstrapped:true,planBootstrappedAt:now()},root);}
  while(processed<maxTasks){state=readState(root);if(state.delivery?.state==='PAUSED'||state.delivery?.state==='OWNER_DECISION_REQUIRED'||openDecisions(root).length)break;let task=chooseNext(state.tasks);
    if(!task){const unresolved=state.tasks.filter(t=>t.state!=='ACCEPTED');if(unresolved.length){setProjectLifecycle('BLOCKED',{lastError:`No eligible task; unresolved states: ${unresolved.map(t=>`${t.id}:${t.state}`).join(', ')}`},root);break;}const completion=await managerCompletion(root,roles.manager);if(completion.verdict==='OWNER_DECISION_REQUIRED')return pauseForAgentDecision(completion,'codex-completion',root);if(completion.verdict==='ADD_TASKS'){const applied=applyManagerPlan(completion,root);if(!applied.tasks?.length){setProjectLifecycle('BLOCKED',{lastError:'Manager requested ADD_TASKS but supplied no new tasks'},root);break;}continue;}if(completion.verdict==='COMPLETE')return {...await finishProject(root),processed,outcomes};throw new Error(`Unsupported completion verdict: ${completion.verdict}`);}
    const brief=await managerTaskBrief(task,root,roles.manager);if(brief.status==='OWNER_DECISION_REQUIRED')return {...pauseForAgentDecision(brief,'codex-manager-task',root,task.id),processed,outcomes};mutateTask(task.id,{managerBrief:brief.brief||'',managerImplementationNotes:brief.implementationNotes||[],verificationFocus:brief.verificationFocus||[],managerRisks:brief.risks||[]},'MANAGER_BRIEF',root);
    let accepted=false;for(let attempt=1;attempt<=maxRepairs;attempt++){task=readState(root).tasks.find(t=>t.id===task.id);const run=await runTask(task.id,roles.developer,root,options.runOptions||{});if(run.status!=='passed'){mutateTask(task.id,{reviewFeedback:`Developer attempt ${attempt} failed. ${run.stderrTail||run.stdoutTail||run.failureFingerprint||'No diagnostic output.'}`},'AUTONOMOUS_REPAIR_CONTEXT',root);if(attempt===maxRepairs){addOwnerDecision({title:`${task.id} exhausted repair attempts`,question:`The developer failed ${maxRepairs} attempts for ${task.title}. Choose how to proceed.`,options:['retry','replan','pause'],recommendation:'replan',impact:'Only this dependency path is blocked.',source:'repair-limit',taskId:task.id},root);break;}continue;}
      const verification=verifyTask(task.id,root);if(!verification.passed){const failed=verification.evidence.filter(e=>e.status==='failed').map(e=>`${e.type}: ${e.source}`).join('; ');mutateTask(task.id,{reviewFeedback:`SHIPSTATE verification failed on attempt ${attempt}: ${failed}`},'AUTONOMOUS_REPAIR_CONTEXT',root);if(attempt===maxRepairs){addOwnerDecision({title:`${task.id} failed deterministic verification`,question:`Verification still fails after ${maxRepairs} attempts. Choose how to proceed.`,options:['retry','replan','pause'],recommendation:'replan',impact:'Only this dependency path is blocked.',source:'verification-limit',taskId:task.id},root);break;}continue;}
      const current=readState(root),currentTask=current.tasks.find(t=>t.id===task.id),runRec=current.runs.find(r=>r.id===currentTask.lastRunId)||current.runs.filter(r=>r.taskId===task.id).at(-1);const review=await reviewerDecision(currentTask,runRec,verification,root,roles.reviewer);mutateTask(task.id,{lastReview:review},'CODE_REVIEW',root);if(review.verdict==='OWNER_DECISION_REQUIRED')return {...pauseForAgentDecision(review,'codex-review',root,task.id),processed,outcomes};if(review.verdict==='APPROVE'){const acceptance=acceptTask(task.id,root,'codex-reviewer');outcomes.push({taskId:task.id,attempt,verified:true,review:'APPROVE',accepted:true,acceptance});processed++;accepted=true;break;}if(review.verdict==='REPAIR'||review.verdict==='REPLAN'){rejectTask(task.id,review.summary||review.repairBrief||review.verdict,root,'codex-reviewer');mutateTask(task.id,{reviewFeedback:review.repairBrief||review.summary||'Reviewer requested repair.',reviewFindings:review.findings||[],priority:review.verdict==='REPLAN'?(task.priority||0)-1000:(task.priority||0)},'AUTONOMOUS_REPAIR_CONTEXT',root);if(review.verdict==='REPLAN'){const replanned=await managerPlan(root,roles.manager);if(replanned.status==='OWNER_DECISION_REQUIRED')return {...pauseForAgentDecision(replanned,'codex-replan',root,task.id),processed,outcomes};applyManagerPlan(replanned,root);break;}if(attempt===maxRepairs)addOwnerDecision({title:`${task.id} failed code review repeatedly`,question:`Codex requested repairs after ${maxRepairs} attempts. Choose how to proceed.`,options:['retry','replan','pause'],recommendation:'replan',impact:'Only this dependency path is blocked.',source:'review-limit',taskId:task.id},root);continue;}throw new Error(`Unsupported reviewer verdict: ${review.verdict}`);}
    if(openDecisions(root).length)break;if(!accepted&&readState(root).delivery?.state==='OWNER_DECISION_REQUIRED')break;
  }
  const final=readState(root);return {sessionId,processed,outcomes,state:final.delivery?.state,remaining:final.tasks.filter(t=>t.state!=='ACCEPTED').length,openOwnerDecisions:openDecisions(root)};
}
export function startDeliveryBackground(options={},root=process.cwd()){if(ACTIVE.has(root))return {started:false,sessionId:ACTIVE.get(root).sessionId,startedAt:ACTIVE.get(root).startedAt};const sessionId=id('delivery-bg'),startedAt=now();const promise=runAutonomousDelivery(options,root).catch(e=>{try{setProjectLifecycle('BLOCKED',{lastError:e.message},root);}catch{}return {error:e.message};}).finally(()=>ACTIVE.delete(root));ACTIVE.set(root,{sessionId,startedAt,promise});return {started:true,sessionId,startedAt};}
export function pauseDelivery(root=process.cwd(),reason='paused by owner'){setProjectLifecycle('PAUSED',{pauseReason:reason,pauseRequestedAt:now()},root);recordDecision({id:id('decision'),type:'delivery-pause',actor:'owner',at:now(),reason},root);return {paused:true,note:'An active bounded task may finish before the controller stops at the next safe boundary.'};}
