import { id,now } from './utils.js';
import { readState,writeState,appendEvent,addTasks,addPlan,mutateTask,mutateDelivery,recordDecision } from './store.js';
import { chooseNext } from './core.js';
import { runTask } from './runner.js';
import { verifyTask } from './verifier.js';
import { acceptTask,rejectTask } from './actions.js';
import { CONTROL_PATHS,readProjectContract } from './project-kit.js';
import { assertHandoverCurrent,setProjectLifecycle,addOwnerDecision } from './handover.js';
import { managerPreflight,managerPlan,managerTaskBrief,reviewerDecision,managerCompletion } from './agent-team.js';
import { diagnoseRepair,repairFeedback,completeRepairEpisode } from './repair.js';
import { finishProject,certifyProject } from './finalize.js';
export { certifyProject } from './finalize.js';

const ACTIVE=new Map();
export function activeDeliveries(){return [...ACTIVE.entries()].map(([root,x])=>({root,sessionId:x.sessionId,startedAt:x.startedAt}));}
export function isDeliveryActive(root=process.cwd()){return ACTIVE.has(root);}
function openDecisions(root){return (readState(root).ownerDecisions||[]).filter(x=>x.status==='OPEN');}
function createAiDecisions(items,source,root,taskId=null){return (items||[]).map(d=>addOwnerDecision({...d,source,taskId},root));}
function normalizeId(value,fallback){return String(value||fallback).toUpperCase().replace(/[^A-Z0-9._-]/g,'-');}
function normalizeTask(raw,index){const idValue=normalizeId(raw.id,`AI-${String(index+1).padStart(3,'0')}`),risk=['low','medium','high'].includes(String(raw.risk||'').toLowerCase())?String(raw.risk).toLowerCase():'medium';return {id:idValue,title:String(raw.title||idValue).slice(0,140),objective:String(raw.objective||raw.title||idValue).slice(0,3000),acceptanceCriteria:(raw.acceptanceCriteria||[]).map(String).filter(Boolean).slice(0,30),verification:(raw.verification||[]).map(String).filter(Boolean).slice(0,20),files:(raw.files||[]).map(String).filter(Boolean).slice(0,50),allowedPaths:(raw.allowedPaths||[]).map(String).filter(Boolean).filter(x=>!CONTROL_PATHS.includes(x)).slice(0,50),protectedPaths:[...new Set([...(raw.protectedPaths||[]).map(String),...CONTROL_PATHS])],evidenceRequired:(raw.evidenceRequired||['command','diff']).map(String).filter(Boolean).slice(0,20),dependsOn:(raw.dependsOn||[]).map(x=>normalizeId(x,x)).filter(Boolean),priority:Number.isFinite(Number(raw.priority))?Number(raw.priority):50,risk,milestone:raw.milestone||null,state:'PENDING',createdAt:now(),updatedAt:now(),source:'codex-manager'};}
function assertTaskGraph(tasks,existingIds){const all=new Set([...existingIds,...tasks.map(t=>t.id)]);for(const t of tasks)for(const d of t.dependsOn)if(!all.has(d))throw new Error(`Manager task ${t.id} depends on unknown task ${d}`);const by=Object.fromEntries(tasks.map(t=>[t.id,t])),visiting=new Set(),done=new Set();const visit=x=>{if(done.has(x)||!by[x])return;if(visiting.has(x))throw new Error(`Manager task graph contains cycle at ${x}`);visiting.add(x);for(const d of by[x].dependsOn)visit(d);visiting.delete(x);done.add(x);};for(const t of tasks)visit(t.id);}
export function normalizeManagerPlan(result,state){if(result?.status==='OWNER_DECISION_REQUIRED')return {status:result.status,decisions:result.decisions||[]};if(result?.status!=='PLAN'&&result?.verdict!=='ADD_TASKS')throw new Error(`Manager returned unsupported plan status: ${result?.status||result?.verdict||'missing'}`);const existing=new Set(state.tasks.map(t=>t.id)),generated=new Set(),tasks=[];for(const [i,raw] of (result.tasks||[]).slice(0,80).entries()){const t=normalizeTask(raw,i);if(existing.has(t.id))continue;if(generated.has(t.id))throw new Error(`Manager returned duplicate task id: ${t.id}`);generated.add(t.id);tasks.push(t);}assertTaskGraph(tasks,existing);for(const t of tasks){if(!t.acceptanceCriteria.length)throw new Error(`Manager task ${t.id} has no acceptance criteria`);if(t.dependsOn.includes(t.id))throw new Error(`Manager task ${t.id} cannot depend on itself`);}return {status:'PLAN',summary:result.summary||'',milestones:result.milestones||[],tasks};}
function applyManagerPlan(result,root){const s=readState(root),normalized=normalizeManagerPlan(result,s);if(normalized.status==='OWNER_DECISION_REQUIRED'){createAiDecisions(normalized.decisions,'codex-manager-plan',root);return normalized;}if(!normalized.tasks.length)return normalized;const plan={id:id('ai-plan'),createdAt:now(),approvedAt:now(),status:'APPROVED_AUTONOMOUS',source:'codex-manager',summary:normalized.summary,milestones:normalized.milestones,tasks:normalized.tasks};addPlan(plan,root);addTasks(normalized.tasks,root);recordDecision({id:id('decision'),type:'autonomous-plan',actor:'codex',at:now(),planId:plan.id,taskCount:normalized.tasks.length},root);return normalized;}
function setHandoverActive(root){const s=readState(root);s.handover={...(s.handover||{}),status:'HANDED_OVER',handedOverAt:s.handover?.handedOverAt||now()};appendEvent('PROJECT_HANDED_OVER',{contractHash:s.handover.contractHash,handover:s.handover},root);writeState(s,root);}
function pauseForAgentDecision(result,source,root,taskId=null){const items=result?.decisions?.length?result.decisions:[{title:'AI team needs owner decision',question:result?.summary||'A material project decision is required before autonomous development can continue.',options:[],recommendation:null,impact:'Only the affected autonomous path is paused.'}];createAiDecisions(items,source,root,taskId);return {paused:true,reason:'owner-decision'};}
function markDelivery(patch,root){return mutateDelivery(patch,'DELIVERY_UPDATED',root);}
async function replanAfterExhaustion(task,reason,root,manager){try{const current=readState(root).tasks.find(t=>t.id===task.id);if(current&&['FAILED','BLOCKED','IMPLEMENTED','VERIFIED'].includes(current.state))rejectTask(task.id,reason,root,'shipstate-repair');mutateTask(task.id,{priority:-10000,reviewFeedback:`Automatic repair exhausted. Replan required. ${reason}`},'AUTONOMOUS_REPLAN_CONTEXT',root);const replanned=await managerPlan(root,manager);if(replanned.status==='OWNER_DECISION_REQUIRED')return pauseForAgentDecision(replanned,'codex-repair-replan',root,task.id);const applied=applyManagerPlan(replanned,root);if(applied.tasks?.length)return {replanned:true,addedTasks:applied.tasks.length};addOwnerDecision({title:`${task.id} needs owner intervention`,question:`Automated diagnosis and replan produced no alternative implementation path for ${task.title}.`,options:['retry','pause'],recommendation:'retry',impact:'Only this dependency path is blocked.',source:'repair-replan-empty',taskId:task.id},root);return {replanned:false};}catch(e){addOwnerDecision({title:`${task.id} replan failed`,question:`Automated repair/replan could not continue: ${e.message}`,options:['retry','pause'],recommendation:'retry',impact:'Only this dependency path is blocked.',source:'repair-replan-error',taskId:task.id},root);return {replanned:false,error:e.message};}}
async function diagnoseAndAttach(task,failure,attempt,root,manager,existingDiagnosis=null){const {episode,diagnosis}=await diagnoseRepair(task,failure,attempt,root,manager,existingDiagnosis);if(diagnosis.status==='OWNER_DECISION_REQUIRED')return {episode,diagnosis,paused:pauseForAgentDecision(diagnosis,'codex-diagnosis',root,task.id)};if(diagnosis.status==='REPLAN')return {episode,diagnosis,replan:true};mutateTask(task.id,{reviewFeedback:repairFeedback(episode),repairEpisodeId:episode.id},'AUTONOMOUS_REPAIR_CONTEXT',root);return {episode,diagnosis};}
export async function runAutonomousDelivery(options={},root=process.cwd()){
 assertHandoverCurrent(root);if(openDecisions(root).length){setProjectLifecycle('OWNER_DECISION_REQUIRED',{waitingOnDecisionId:openDecisions(root)[0].id},root);return {paused:true,reason:'open-owner-decision'};}const contract=readProjectContract(root),roles={...contract.roles,...Object.fromEntries(Object.entries(options.roles||{}).filter(([,v])=>Boolean(v)))},sessionId=id('delivery'),maxTasks=Number(options.maxTasks||contract.limits?.maxTasksPerSession||100),maxRepairs=Number(options.maxRepairs||contract.limits?.maxRepairCycles||3);let processed=0;const outcomes=[];
 let state=readState(root);if(!state.delivery?.preflightPassed){setProjectLifecycle('HANDOVER_REVIEW',{sessionId},root);const preflight=await managerPreflight(root,roles.manager);if(preflight.status!=='READY')return pauseForAgentDecision(preflight,'codex-preflight',root);markDelivery({preflightPassed:true,preflightPassedAt:now()},root);}setHandoverActive(root);setProjectLifecycle('AUTONOMOUS_DEVELOPMENT',{sessionId,pauseReason:null,waitingOnDecisionId:null},root);
 state=readState(root);if(state.delivery?.forceReplan){const replanned=await managerPlan(root,roles.manager);if(replanned.status==='OWNER_DECISION_REQUIRED')return pauseForAgentDecision(replanned,'codex-owner-replan',root);applyManagerPlan(replanned,root);markDelivery({forceReplan:false,planBootstrapped:true,lastReplannedAt:now()},root);}else if(!state.delivery?.planBootstrapped){const planResult=await managerPlan(root,roles.manager);if(planResult.status==='OWNER_DECISION_REQUIRED')return pauseForAgentDecision(planResult,'codex-manager-plan',root);applyManagerPlan(planResult,root);markDelivery({planBootstrapped:true,planBootstrappedAt:now()},root);}
 while(processed<maxTasks){state=readState(root);if(['PAUSED','OWNER_DECISION_REQUIRED'].includes(state.delivery?.state)||openDecisions(root).length)break;let task=chooseNext(state.tasks);if(!task){const unresolved=state.tasks.filter(t=>t.state!=='ACCEPTED');if(unresolved.length){setProjectLifecycle('BLOCKED',{lastError:`No eligible task; unresolved states: ${unresolved.map(t=>`${t.id}:${t.state}`).join(', ')}`},root);break;}const completion=await managerCompletion(root,roles.manager);if(completion.verdict==='OWNER_DECISION_REQUIRED')return pauseForAgentDecision(completion,'codex-completion',root);if(completion.verdict==='ADD_TASKS'){const applied=applyManagerPlan(completion,root);if(!applied.tasks?.length){setProjectLifecycle('BLOCKED',{lastError:'Manager requested ADD_TASKS but supplied no new tasks'},root);break;}continue;}if(completion.verdict==='COMPLETE')return {...await finishProject(root),processed,outcomes};throw new Error(`Unsupported completion verdict: ${completion.verdict}`);}
  const brief=await managerTaskBrief(task,root,roles.manager);if(brief.status==='OWNER_DECISION_REQUIRED')return {...pauseForAgentDecision(brief,'codex-manager-task',root,task.id),processed,outcomes};mutateTask(task.id,{managerBrief:brief.brief||'',managerImplementationNotes:brief.implementationNotes||[],verificationFocus:brief.verificationFocus||[],managerRisks:brief.risks||[]},'MANAGER_BRIEF',root);let accepted=false,replanned=false;
  for(let attempt=1;attempt<=maxRepairs;attempt++){task=readState(root).tasks.find(t=>t.id===task.id);const run=await runTask(task.id,roles.developer,root,options.runOptions||{});if(run.status!=='passed'){const failure={type:run.timedOut?'timeout':'execution',summary:`Developer attempt ${attempt} failed`,stdout:run.stdoutTail,stderr:run.stderrTail,fingerprint:run.failureFingerprint,evidence:[`exitCode=${run.exitCode}`,`changedFiles=${(run.changedFiles||[]).join(',')}`]},diag=await diagnoseAndAttach(task,failure,attempt,root,roles.manager);if(diag.paused)return {...diag.paused,processed,outcomes};if(diag.replan||attempt===maxRepairs){await replanAfterExhaustion(task,diag.diagnosis?.rootCause||failure.summary,root,roles.manager);replanned=true;break;}continue;}
   const verification=verifyTask(task.id,root);if(!verification.passed){const failed=verification.evidence.filter(e=>e.status==='failed').map(e=>`${e.type}: ${e.source}`),failure={type:'test',summary:`SHIPSTATE verification failed: ${failed.join('; ')}`,evidence:failed,stdout:verification.evidence.map(e=>e.stdout||'').join('\n').slice(-5000),stderr:verification.evidence.map(e=>e.stderr||'').join('\n').slice(-5000)},diag=await diagnoseAndAttach(task,failure,attempt,root,roles.manager);if(diag.paused)return {...diag.paused,processed,outcomes};if(diag.replan||attempt===maxRepairs){await replanAfterExhaustion(task,diag.diagnosis?.rootCause||failure.summary,root,roles.manager);replanned=true;break;}continue;}
   const current=readState(root),currentTask=current.tasks.find(t=>t.id===task.id),runRec=current.runs.find(r=>r.id===currentTask.lastRunId)||current.runs.filter(r=>r.taskId===task.id).at(-1),review=await reviewerDecision(currentTask,runRec,verification,root,roles.reviewer);mutateTask(task.id,{lastReview:review},'CODE_REVIEW',root);if(review.verdict==='OWNER_DECISION_REQUIRED')return {...pauseForAgentDecision(review,'codex-review',root,task.id),processed,outcomes};if(review.verdict==='APPROVE'){if(currentTask.repairEpisodeId)completeRepairEpisode(currentTask.repairEpisodeId,{passed:true,review:'APPROVE'},root);const acceptance=acceptTask(task.id,root,'codex-reviewer');outcomes.push({taskId:task.id,attempt,verified:true,review:'APPROVE',accepted:true,acceptance});processed++;accepted=true;break;}if(review.verdict==='REPAIR'||review.verdict==='REPLAN'){rejectTask(task.id,review.summary||review.repairBrief||review.verdict,root,'codex-reviewer');const failure={type:'review',summary:review.summary||'Reviewer requested repair',evidence:(review.findings||[]).map(x=>`${x.severity||'normal'}:${x.file||''}:${x.issue||''}`)},diag=await diagnoseAndAttach(task,failure,attempt,root,roles.manager,review);mutateTask(task.id,{reviewFindings:review.findings||[]},'AUTONOMOUS_REPAIR_CONTEXT',root);if(diag.paused)return {...diag.paused,processed,outcomes};if(review.verdict==='REPLAN'||diag.replan||attempt===maxRepairs){await replanAfterExhaustion(task,review.rootCause||review.summary||'review requested replan',root,roles.manager);replanned=true;break;}continue;}throw new Error(`Unsupported reviewer verdict: ${review.verdict}`);}
  if(openDecisions(root).length)break;if(replanned)continue;if(!accepted&&readState(root).delivery?.state==='OWNER_DECISION_REQUIRED')break;
 }
 const final=readState(root);return {sessionId,processed,outcomes,state:final.delivery?.state,remaining:final.tasks.filter(t=>t.state!=='ACCEPTED').length,openOwnerDecisions:openDecisions(root)};
}
export function startDeliveryBackground(options={},root=process.cwd()){if(ACTIVE.has(root))return {started:false,sessionId:ACTIVE.get(root).sessionId,startedAt:ACTIVE.get(root).startedAt};const sessionId=id('delivery-bg'),startedAt=now(),promise=runAutonomousDelivery(options,root).catch(e=>{try{setProjectLifecycle('BLOCKED',{lastError:e.message},root);}catch{}return {error:e.message};}).finally(()=>ACTIVE.delete(root));ACTIVE.set(root,{sessionId,startedAt,promise});return {started:true,sessionId,startedAt};}
export function pauseDelivery(root=process.cwd(),reason='paused by owner'){setProjectLifecycle('PAUSED',{pauseReason:reason,pauseRequestedAt:now()},root);recordDecision({id:id('decision'),type:'delivery-pause',actor:'owner',at:now(),reason},root);return {paused:true,note:'An active bounded task may finish before the controller stops at the next safe boundary.'};}
