import { id,now,runShell } from './utils.js';
import { readState,recordEvidence,refreshProfile } from './store.js';
import { readProjectContract } from './project-kit.js';
import { setProjectLifecycle,addOwnerDecision } from './handover.js';
import { certifyQuality } from './quality.js';

function certificationCommands(state,contract){return [...new Set([...(state.profile?.commands?.test?[state.profile.commands.test]:[]),...(state.profile?.commands?.typecheck?[state.profile.commands.typecheck]:[]),...(state.profile?.commands?.lint?[state.profile.commands.lint]:[]),...(state.profile?.commands?.build?[state.profile.commands.build]:[]),...(contract.delivery?.buildCommands||[])].filter(Boolean))];}
export function certifyProject(root=process.cwd()){refreshProfile(root);const s=readState(root),contract=readProjectContract(root),notAccepted=s.tasks.filter(t=>t.state!=='ACCEPTED');if(notAccepted.length)return {passed:false,reason:`${notAccepted.length} tasks are not ACCEPTED`,tasks:notAccepted.map(t=>({id:t.id,state:t.state}))};const commands=certificationCommands(s,contract);if(!commands.length)return {passed:false,reason:'No deterministic project certification commands were detected or configured'};const evidence=[];let passed=true;for(const command of commands){const r=runShell(command,root,process.env,30*60*1000),ev={id:id('ev'),taskId:'PROJECT',type:'project-certification',source:command,status:r.status===0?'passed':'failed',exitCode:r.status??1,stdout:(r.stdout||'').slice(-8000),stderr:(r.stderr||'').slice(-8000),createdAt:now()};evidence.push(ev);if(r.status!==0)passed=false;}recordEvidence(evidence,root);return {passed,evidence};}
function runDeliveryCommands(commands,type,root){const evidence=[];let passed=true;for(const command of commands||[]){const r=runShell(command,root,process.env,45*60*1000),ev={id:id('ev'),taskId:'PROJECT',type,source:command,status:r.status===0?'passed':'failed',exitCode:r.status??1,stdout:(r.stdout||'').slice(-8000),stderr:(r.stderr||'').slice(-8000),createdAt:now()};evidence.push(ev);if(r.status!==0){passed=false;break;}}if(evidence.length)recordEvidence(evidence,root);return {passed,evidence};}
function gateAuthorized(gate,state){return Boolean(state.delivery?.authorizedGates?.[gate]);}
function requireGate(gate,title,question,root){const existing=(readState(root).ownerDecisions||[]).find(d=>d.status==='OPEN'&&d.gate===gate);if(existing)return existing;return addOwnerDecision({gate,title,question,options:['approve','pause'],recommendation:'approve',impact:`${gate} waits for explicit owner authorization.`,source:'shipstate-gate'},root);}
function rollbackIfConfigured(contract,root){return (contract.delivery?.rollbackCommands||[]).length?runDeliveryCommands(contract.delivery.rollbackCommands,'rollback',root):null;}
function deployAndValidate(contract,root){setProjectLifecycle('DEPLOYMENT',{},root);const deployed=runDeliveryCommands(contract.delivery?.deployCommands,'deployment',root);if(!deployed.passed){setProjectLifecycle('BLOCKED',{lastError:'deployment failed'},root);return {passed:false,deployment:deployed};}setProjectLifecycle('DELIVERY_VALIDATION',{},root);const smoke=runDeliveryCommands(contract.delivery?.smokeCommands,'production-smoke',root);if(!smoke.passed){const rollback=rollbackIfConfigured(contract,root),rollbackAttempted=Boolean(rollback),rollbackFailed=Boolean(rollback&&!rollback.passed);setProjectLifecycle('BLOCKED',{lastError:rollbackFailed?'production smoke failed and rollback failed':'production smoke failed',rollbackAttempted,rollbackFailed},root);return {passed:false,deployment:deployed,smoke,rollback};}return {passed:true,deployment:deployed,smoke};}
export async function finishProject(root=process.cwd()){
 setProjectLifecycle('INTERNAL_CERTIFICATION',{},root);const cert=certifyProject(root);if(!cert.passed){setProjectLifecycle('FAILED_CERTIFICATION',{lastError:cert.reason||'project certification failed'},root);return {complete:false,certification:cert};}const quality=await certifyQuality(root);if(!quality.passed){setProjectLifecycle('FAILED_CERTIFICATION',{lastError:quality.reason||'quality certification failed'},root);return {complete:false,certification:cert,quality};}setProjectLifecycle('RELEASE_CANDIDATE',{},root);const contract=readProjectContract(root);let state=readState(root);if(contract.autonomy?.release==='owner_gate'&&!gateAuthorized('release',state)){requireGate('release','Release approval required','SHIPSTATE deterministic and quality certification passed. Approve release/deployment continuation?',root);return {complete:false,awaiting:'release',certification:cert,quality};}state=readState(root);const deploymentMode=contract.autonomy?.deployment;if(deploymentMode==='owner_gate'&&!gateAuthorized('deployment',state)){requireGate('deployment','Deployment approval required','The certified release candidate is ready. Approve deployment?',root);return {complete:false,awaiting:'deployment',certification:cert,quality};}const shouldDeploy=deploymentMode==='automatic'||(deploymentMode==='owner_gate'&&gateAuthorized('deployment',readState(root)));let deliveryEvidence=null;if(shouldDeploy&&(contract.delivery?.deployCommands||[]).length){deliveryEvidence=deployAndValidate(contract,root);if(!deliveryEvidence.passed)return {complete:false,certification:cert,quality,...deliveryEvidence};}setProjectLifecycle('DELIVERY_READY',{deployed:Boolean(deliveryEvidence?.passed)},root);if(contract.autonomy?.release==='automatic'||gateAuthorized('release',readState(root))){setProjectLifecycle('DELIVERED',{deployed:Boolean(deliveryEvidence?.passed)},root);return {complete:true,delivered:true,certification:cert,quality,...(deliveryEvidence||{})};}return {complete:true,deliveryReady:true,certification:cert,quality,...(deliveryEvidence||{})};
}
