import fs from 'node:fs';
import path from 'node:path';
import { id,now,sha256 } from './utils.js';
import { isGitRepo,isClean } from './git.js';
import { readState,writeState,appendEvent,recordDecision } from './store.js';
import { ensureProjectKit,readProjectContract,setProjectDecision,documentStatus,readProjectDocuments,REQUIRED_DECISIONS,REQUIRED_DOCUMENTS,CONTROL_PATHS,PROJECT_CONFIG,projectConfigPath,projectDocumentPath } from './project-kit.js';

export const PROJECT_STATES=Object.freeze(['PROJECT_SETUP','HANDOVER_REVIEW','READY_FOR_HANDOVER','AUTONOMOUS_DEVELOPMENT','OWNER_DECISION_REQUIRED','PAUSED','INTERNAL_CERTIFICATION','RELEASE_CANDIDATE','DEPLOYMENT','DELIVERY_VALIDATION','DELIVERY_READY','DELIVERED','BLOCKED','FAILED_CERTIFICATION']);

export function projectContractHash(root=process.cwd()){const contract=readProjectContract(root);const docs=readProjectDocuments(root,Number.MAX_SAFE_INTEGER);return sha256(JSON.stringify({contract,docs}));}
function missingConfigDocuments(root){return REQUIRED_DOCUMENTS.map(doc=>{const p=projectDocumentPath(root,doc),exists=fs.existsSync(p),text=exists?fs.readFileSync(p,'utf8'):'',words=text.replace(/<!--[^]*?-->/g,' ').trim().split(/\s+/).filter(Boolean).length,todo=/SHIPSTATE:TODO/i.test(text);return {...doc,path:path.relative(root,p),exists,todo,words,complete:exists&&!todo&&words>=20,decisionStatus:'pending'};});}
export function handoverAudit(root=process.cwd()){
  const blockers=[],configExists=fs.existsSync(projectConfigPath(root));let contract=null,docs=[];
  if(!configExists){blockers.push({type:'config',key:PROJECT_CONFIG,reason:`missing ${PROJECT_CONFIG}; run shipstate handover init`});docs=missingConfigDocuments(root);}else{contract=readProjectContract(root);docs=documentStatus(root);}
  for(const d of docs)if(!d.complete)blockers.push({type:'document',key:d.key,path:d.path,reason:!d.exists?'missing':d.todo?'contains SHIPSTATE:TODO marker':`too little substantive content (${d.words} words)`});
  if(contract)for(const def of REQUIRED_DECISIONS){const value=contract.decisions?.[def.key]||{};if(value.status!=='approved'&&value.status!=='not_applicable')blockers.push({type:'decision',key:def.key,reason:def.label});else if(value.status==='not_applicable'&&!def.allowNA)blockers.push({type:'decision',key:def.key,reason:'not_applicable is not permitted'});}
  if(contract)for(const role of ['manager','reviewer','developer','verifier'])if(!contract.roles?.[role])blockers.push({type:'role',key:role,reason:'role is not assigned'});
  const autoDeploy=contract?.autonomy?.deployment==='automatic';if(autoDeploy&&!(contract.delivery?.deployCommands||[]).length)blockers.push({type:'deployment',key:'deployCommands',reason:'automatic deployment requires at least one deploy command'});if(autoDeploy&&!(contract.delivery?.smokeCommands||[]).length)blockers.push({type:'deployment',key:'smokeCommands',reason:'automatic deployment requires at least one production smoke command'});
  const gitRepo=isGitRepo(root);if(!gitRepo)blockers.push({type:'git',key:'repository',reason:'project must be a Git repository'});const gitClean=gitRepo?isClean(root):false;if(gitRepo&&!gitClean)blockers.push({type:'git',key:'clean',reason:`commit project documents and ${PROJECT_CONFIG} before handover`});
  const status=blockers.length?'HANDOVER_REVIEW':'READY_FOR_HANDOVER';return {status,ready:blockers.length===0,created:[],documents:docs,decisions:contract?.decisions||{},roles:contract?.roles||{},autonomy:contract?.autonomy||{},gitClean,contractHash:contract?projectContractHash(root):null,blockers};
}
export function initializeHandover(root=process.cwd()){const kit=ensureProjectKit(root);const s=readState(root);s.handover={...(s.handover||{}),status:'HANDOVER_REVIEW',initializedAt:s.handover?.initializedAt||now()};s.delivery={...(s.delivery||{}),state:'PROJECT_SETUP'};appendEvent('HANDOVER_INITIALIZED',{created:kit.created},root);writeState(s,root);return {created:kit.created,audit:handoverAudit(root)};}
export function decideProject(key,status,note='',root=process.cwd()){const contract=setProjectDecision(key,status,note,root);const decision={id:id('decision'),type:'project-decision',key,status,note,actor:'owner',at:now()};recordDecision(decision,root);return {decision,contract};}
export function acceptHandover(root=process.cwd()){
  const audit=handoverAudit(root);if(!audit.ready)throw new Error(`Project is not ready for handover: ${audit.blockers.map(x=>`${x.key}: ${x.reason}`).join('; ')}`);const s=readState(root);const contract=readProjectContract(root);s.handover={status:'READY_FOR_HANDOVER',acceptedAt:now(),contractHash:audit.contractHash,documents:audit.documents.map(d=>({key:d.key,path:d.path})),roles:contract.roles,autonomy:contract.autonomy};s.team={...(s.team||{}),...contract.roles};s.delivery={...(s.delivery||{}),state:'READY_FOR_HANDOVER',startedAt:null,completedAt:null,lastError:null,planBootstrapped:false,preflightPassed:false,forceReplan:false,authorizedGates:{},waitingOnDecisionId:null,pauseReason:null};s.project.protectedPaths=[...new Set([...(s.project.protectedPaths||[]),...CONTROL_PATHS])];appendEvent('HANDOVER_ACCEPTED',{contractHash:audit.contractHash,roles:contract.roles,autonomy:contract.autonomy,handover:s.handover,team:s.team,delivery:s.delivery,protectedPaths:s.project.protectedPaths},root);writeState(s,root);recordDecision({id:id('decision'),type:'handover-accepted',actor:'owner',at:now(),contractHash:audit.contractHash},root);return s.handover;
}
export function assertHandoverCurrent(root=process.cwd()){const s=readState(root);if(!['READY_FOR_HANDOVER','HANDED_OVER'].includes(s.handover?.status))throw new Error('Project has not been accepted for handover. Run: shipstate handover accept');const current=projectContractHash(root);if(current!==s.handover.contractHash)throw new Error('Project handover documents/config changed after approval. Re-run handover audit and accept.');return s.handover;}
export function setProjectLifecycle(state,patch={},root=process.cwd()){if(!PROJECT_STATES.includes(state))throw new Error(`Unknown project lifecycle state: ${state}`);const s=readState(root);s.delivery={...(s.delivery||{}),...patch,state,updatedAt:now()};if(state==='AUTONOMOUS_DEVELOPMENT'&&!s.delivery.startedAt)s.delivery.startedAt=now();if(state==='DELIVERED')s.delivery.completedAt=now();appendEvent('PROJECT_LIFECYCLE',{state,patch:s.delivery},root);writeState(s,root);return s.delivery;}
export function addOwnerDecision(input,root=process.cwd()){
  const s=readState(root);const item={id:input.id||id('owner'),title:input.title||'Owner decision required',question:input.question||input.title||'Decision required',options:Array.isArray(input.options)?input.options:[],recommendation:input.recommendation||null,impact:input.impact||null,source:input.source||'ai-team',taskId:input.taskId||null,gate:input.gate||null,status:'OPEN',createdAt:now()};s.ownerDecisions||=[];s.ownerDecisions.push(item);appendEvent('OWNER_DECISION_OPENED',{decision:item},root);writeState(s,root);setProjectLifecycle('OWNER_DECISION_REQUIRED',{waitingOnDecisionId:item.id},root);return item;
}
export function resolveOwnerDecision(decisionId,resolution,note='',root=process.cwd()){
  const s=readState(root);const d=(s.ownerDecisions||[]).find(x=>x.id===decisionId);if(!d)throw new Error(`Unknown owner decision: ${decisionId}`);if(d.status!=='OPEN')throw new Error(`Decision ${decisionId} is already ${d.status}`);if(d.options.length&&!d.options.some(o=>(typeof o==='string'?o:o.value||o.id)===resolution))throw new Error(`Resolution must be one of: ${d.options.map(o=>typeof o==='string'?o:o.value||o.id).join(', ')}`);d.status='RESOLVED';d.resolution=resolution;d.note=note;d.resolvedAt=now();s.delivery={...(s.delivery||{}),authorizedGates:{...(s.delivery?.authorizedGates||{})}};if(d.gate&&resolution==='approve')s.delivery.authorizedGates[d.gate]=true;if(resolution==='replan')s.delivery.forceReplan=true;appendEvent('OWNER_DECISION_RESOLVED',{decisionId,resolution,note,gate:d.gate||null},root);writeState(s,root);recordDecision({id:id('decision'),type:'owner-decision',actor:'owner',decisionId,resolution,note,gate:d.gate||null,at:now()},root);const latest=readState(root);const remaining=(latest.ownerDecisions||[]).filter(x=>x.status==='OPEN');if(!remaining.length&&latest.delivery?.state==='OWNER_DECISION_REQUIRED')setProjectLifecycle('PAUSED',{waitingOnDecisionId:null,pauseReason:resolution==='pause'?'paused by owner':'owner decision resolved; resume autonomous development'},root);return d;
}
export function handoverStatus(root=process.cwd()){const s=readState(root);return {handover:s.handover,delivery:s.delivery,team:s.team,openOwnerDecisions:(s.ownerDecisions||[]).filter(x=>x.status==='OPEN'),audit:handoverAudit(root)};}
