import fs from 'node:fs';
import path from 'node:path';
import { id,now,estimateTokens } from './utils.js';
import { paths,readState,recordEvidence,recordIntelligence,recordMetric } from './store.js';
import { readProjectContract,readProjectDocuments } from './project-kit.js';
import { queryProvider } from './providers/index.js';

function norm(v){return String(v||'').toLowerCase();}
export function deriveQualityProfile(root=process.cwd()){
 const contract=readProjectContract(root),s=readState(root),classes=(contract.project?.classes||[]).map(norm),platforms=(contract.project?.platforms||[]).map(norm),frameworks=(s.profile?.frameworks||[]).map(norm),languages=(s.profile?.languages||[]).map(norm);const web=classes.some(x=>/web|saas/.test(x))||platforms.includes('web')||frameworks.some(x=>/react|next|vue|svelte|angular/.test(x)),ios=platforms.includes('ios')||languages.includes('swift')||frameworks.some(x=>/swift/.test(x)),android=platforms.includes('android')||languages.includes('kotlin')||frameworks.some(x=>/compose/.test(x)),cross=frameworks.some(x=>/flutter|react native/.test(x))||languages.includes('dart');const required=new Set(['security']);if(web){required.add('accessibility');required.add('responsive');required.add('browser-e2e');required.add('performance');required.add('ui-consistency');}if(ios||cross){required.add('ios-accessibility');required.add('safe-area');required.add('device-orientation');required.add('background-resume');}if(android||cross){required.add('android-accessibility');required.add('touch-interaction');required.add('device-classes');required.add('background-resume');}if((contract.project?.publicSurfaces||[]).some(x=>x.discoverability==='required'))required.add('discoverability');for(const [k,v] of Object.entries(contract.qualityProfiles||{})){if(v==='required')required.add(k);if(v==='off')required.delete(k);}return {web,ios,android,crossPlatform:cross,required:[...required].sort(),publicSurfaces:contract.project?.publicSurfaces||[],configured:contract.qualityProfiles||{}};
}
function advisoryChecks(docs,profile){const ux=docs.ux||'',fe=docs.frontend||'',test=docs.testing||'',issues=[];const expect=(ok,area,message)=>{if(!ok)issues.push({area,severity:'medium',message});};if(profile.web){expect(/accessib|keyboard|focus|screen reader|aria/i.test(`${ux}\n${fe}\n${test}`),'accessibility','Web project does not clearly record keyboard/focus/screen-reader expectations.');expect(/responsive|breakpoint|mobile|viewport/i.test(`${ux}\n${fe}`),'responsive','Web project does not clearly record responsive behavior.');expect(/browser/i.test(`${fe}\n${test}`),'browser-support','Browser support/certification matrix is not explicit.');}if(profile.ios||profile.crossPlatform){expect(/safe.?area/i.test(`${ux}\n${fe}`),'ios','Safe-area behavior is not explicit.');expect(/voiceover|dynamic type/i.test(`${ux}\n${test}`),'ios-accessibility','VoiceOver/Dynamic Type expectations are not explicit.');}if(profile.android||profile.crossPlatform)expect(/talkback|compose|android/i.test(`${ux}\n${fe}\n${test}`),'android','Android/TalkBack platform behavior is not explicit.');return issues;}
export async function adviseUi(root=process.cwd()){
 const profile=deriveQualityProfile(root),docs=readProjectDocuments(root,12000),issues=advisoryChecks(docs,profile),query=[readState(root).project.name,...(readProjectContract(root).project?.classes||[]),...(readProjectContract(root).project?.platforms||[])].join(' ').trim();let provider=null;if(profile.web||profile.ios||profile.android||profile.crossPlatform)provider=await queryProvider('ui-intelligence',{action:'design-system',query:query||'software application'},root,{uiTask:true,prepare:false});const result={version:1,generatedAt:now(),advisoryOnly:true,profile,issues,provider:provider?.available?{id:provider.provider,latencyMs:provider.latencyMs,result:provider.result}:{id:provider?.provider||null,available:false,error:provider?.error||null}};const p=path.join(paths(root).advisories,'ui.json');fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(result,null,2)+'\n');recordMetric('providers',{at:result.generatedAt,provider:provider?.provider||'builtin-ui-advisory',capability:'ui-intelligence',latencyMs:provider?.latencyMs||0,outputTokens:estimateTokens(JSON.stringify(provider?.result||issues)),available:Boolean(provider?.available)},root);return {...result,path:p};
}
export async function certifyQuality(root=process.cwd()){
 const profile=deriveQualityProfile(root),contract=readProjectContract(root),evidence=[],reports=[];for(const surface of contract.project?.publicSurfaces||[]){if(surface.discoverability!=='required')continue;if(!surface.url){const ev={id:id('ev'),taskId:'PROJECT',type:'discoverability',source:surface.id||surface.kind||'public-surface',status:'failed',createdAt:now(),stderr:'Required public surface has no URL for deterministic discoverability certification.'};evidence.push(ev);continue;}const q=await queryProvider('discoverability',{url:surface.url,checkSiteFiles:true},root,{publicSurface:true,prepare:false});const passed=Boolean(q.available&&q.result?.passed),ev={id:id('ev'),taskId:'PROJECT',type:'discoverability',source:surface.url,status:passed?'passed':'failed',createdAt:now(),stdout:JSON.stringify(q.result||{}).slice(-8000),stderr:q.error||(!passed?'discoverability checks failed':'')};evidence.push(ev);reports.push({surface,provider:q.provider,latencyMs:q.latencyMs,passed,result:q.result});recordMetric('providers',{at:now(),provider:q.provider||'none',capability:'discoverability',latencyMs:q.latencyMs||0,available:q.available,passed},root);}if(evidence.length)recordEvidence(evidence,root);const passed=evidence.every(e=>e.status==='passed');recordIntelligence({quality:{profile,lastCertifiedAt:now(),passed,reports}},'QUALITY_CERTIFIED',root);return {passed,profile,evidence,reports,reason:passed?null:evidence.find(e=>e.status==='failed')?.stderr||'quality certification failed'};
}
