import fs from 'node:fs';
import path from 'node:path';
import { id,now,estimateTokens,runShell } from './utils.js';
import { paths,readState,recordEvidence,recordIntelligence,recordMetric } from './store.js';
import { readProjectContract,readProjectDocuments } from './project-kit.js';
import { queryProvider } from './providers/index.js';
import { classifyCommand } from './evidence.js';

function norm(v){return String(v||'').toLowerCase();}
export function deriveQualityProfile(root=process.cwd()){
 const contract=readProjectContract(root),s=readState(root),classes=(contract.project?.classes||[]).map(norm),platforms=(contract.project?.platforms||[]).map(norm),frameworks=(s.profile?.frameworks||[]).map(norm);const web=classes.some(x=>/web|saas/.test(x))||platforms.includes('web')||frameworks.some(x=>/react|next|vue|svelte|angular/.test(x)),cross=frameworks.some(x=>/flutter|react-native|react native/.test(x)),ios=platforms.includes('ios')||platforms.includes('iphone')||platforms.includes('ipad')||cross,android=platforms.includes('android')||frameworks.includes('android')||cross;const required=new Set(['security']);if(web){required.add('accessibility');required.add('responsive');required.add('browser-e2e');required.add('performance');required.add('ui-consistency');}if(ios){required.add('ios-accessibility');required.add('safe-area');required.add('device-orientation');required.add('background-resume');}if(android){required.add('android-accessibility');required.add('touch-interaction');required.add('device-classes');required.add('background-resume');}if((contract.project?.publicSurfaces||[]).some(x=>x.discoverability==='required'))required.add('discoverability');for(const [k,v] of Object.entries(contract.qualityProfiles||{})){if(v==='required')required.add(k);if(v==='off')required.delete(k);}return {web,ios,android,crossPlatform:cross,required:[...required].sort(),publicSurfaces:contract.project?.publicSurfaces||[],configured:contract.qualityProfiles||{}};
}
function advisoryChecks(docs,profile){const ux=docs.ux||'',fe=docs.frontend||'',test=docs.testing||'',issues=[];const expect=(ok,area,message)=>{if(!ok)issues.push({area,severity:'medium',message});};if(profile.web){expect(/accessib|keyboard|focus|screen reader|aria/i.test(`${ux}\n${fe}\n${test}`),'accessibility','Web project does not clearly record keyboard/focus/screen-reader expectations.');expect(/responsive|breakpoint|mobile|viewport/i.test(`${ux}\n${fe}`),'responsive','Web project does not clearly record responsive behavior.');expect(/browser/i.test(`${fe}\n${test}`),'browser-support','Browser support/certification matrix is not explicit.');}if(profile.ios||profile.crossPlatform){expect(/safe.?area/i.test(`${ux}\n${fe}`),'ios','Safe-area behavior is not explicit.');expect(/voiceover|dynamic type/i.test(`${ux}\n${test}`),'ios-accessibility','VoiceOver/Dynamic Type expectations are not explicit.');}if(profile.android||profile.crossPlatform)expect(/talkback|compose|android/i.test(`${ux}\n${fe}\n${test}`),'android','Android/TalkBack platform behavior is not explicit.');return issues;}
export async function adviseUi(root=process.cwd()){
 const profile=deriveQualityProfile(root),docs=readProjectDocuments(root,12000),issues=advisoryChecks(docs,profile),query=[readState(root).project.name,...(readProjectContract(root).project?.classes||[]),...(readProjectContract(root).project?.platforms||[])].join(' ').trim();let provider=null;if(profile.web||profile.ios||profile.android||profile.crossPlatform)provider=await queryProvider('ui-intelligence',{action:'design-system',query:query||'software application'},root,{uiTask:true,prepare:false});const result={version:1,generatedAt:now(),advisoryOnly:true,profile,issues,provider:provider?.available?{id:provider.provider,latencyMs:provider.latencyMs,result:provider.result}:{id:provider?.provider||null,available:false,error:provider?.error||null}};const p=path.join(paths(root).advisories,'ui.json');fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(result,null,2)+'\n');recordMetric('providers',{at:result.generatedAt,provider:provider?.provider||'builtin-ui-advisory',capability:'ui-intelligence',latencyMs:provider?.latencyMs||0,outputTokens:estimateTokens(JSON.stringify(provider?.result||issues)),available:Boolean(provider?.available)},root);return {...result,path:p};
}
function commandsFor(contract,dimension){const raw=contract.qualityCertification?.commands?.[dimension];if(Array.isArray(raw))return raw.map(String).filter(Boolean);if(typeof raw==='string'&&raw.trim())return [raw.trim()];return [];}
function matchingExistingEvidence(state,dimension){const mapped={security:['security'],performance:['performance'],'browser-e2e':['browser']}[dimension]||[];return (state.evidence||[]).find(e=>e.status==='passed'&&(e.dimension===dimension||e.type===dimension||mapped.includes(e.type)||(e.type==='project-certification'&&mapped.includes(classifyCommand(e.source||'').type))))||null;}
function runDimensionCommands(root,dimension,commands){const evidence=[];for(const command of commands){const r=runShell(command,root,process.env,30*60*1000);evidence.push({id:id('ev'),taskId:'PROJECT',type:'quality',dimension,source:command,status:r.status===0?'passed':'failed',exitCode:r.status??1,stdout:(r.stdout||'').slice(-8000),stderr:(r.stderr||'').slice(-8000),createdAt:now()});if(r.status!==0)break;}return evidence;}
export async function certifyQuality(root=process.cwd()){
 const profile=deriveQualityProfile(root),contract=readProjectContract(root),state=readState(root),evidence=[],reports=[],missing=[],reusedEvidence=[];
 for(const dimension of profile.required){
  if(dimension==='discoverability')continue;const commands=commandsFor(contract,dimension);if(commands.length){const evs=runDimensionCommands(root,dimension,commands);evidence.push(...evs);if(evs.some(e=>e.status!=='passed'))missing.push(dimension);continue;}const reused=matchingExistingEvidence(state,dimension);if(reused){reusedEvidence.push({dimension,evidenceId:reused.id||null,type:reused.type,source:reused.source});continue;}missing.push(dimension);evidence.push({id:id('ev'),taskId:'PROJECT',type:'quality',dimension,source:'quality certification strategy',status:'failed',createdAt:now(),stderr:`Required quality dimension ${dimension} has no deterministic evidence. Configure shipstate.project.json qualityCertification.commands.${dimension} or produce matching evidence.`});
 }
 for(const surface of contract.project?.publicSurfaces||[]){if(surface.discoverability!=='required')continue;if(!surface.url){const ev={id:id('ev'),taskId:'PROJECT',type:'discoverability',dimension:'discoverability',source:surface.id||surface.kind||'public-surface',status:'failed',createdAt:now(),stderr:'Required public surface has no URL for deterministic discoverability certification.'};evidence.push(ev);missing.push('discoverability');continue;}const q=await queryProvider('discoverability',{url:surface.url,checkSiteFiles:true},root,{publicSurface:true,prepare:false});const passed=Boolean(q.available&&q.result?.passed),ev={id:id('ev'),taskId:'PROJECT',type:'discoverability',dimension:'discoverability',source:surface.url,status:passed?'passed':'failed',createdAt:now(),stdout:JSON.stringify(q.result||{}).slice(-8000),stderr:q.error||(!passed?'discoverability checks failed':'')};evidence.push(ev);reports.push({surface,provider:q.provider,latencyMs:q.latencyMs,passed,result:q.result});recordMetric('providers',{at:now(),provider:q.provider||'none',capability:'discoverability',latencyMs:q.latencyMs||0,available:q.available,passed},root);if(!passed)missing.push('discoverability');}
 if(evidence.length)recordEvidence(evidence,root);const uniqueMissing=[...new Set(missing)],passed=uniqueMissing.length===0&&evidence.every(e=>e.status==='passed');recordIntelligence({quality:{profile,lastCertifiedAt:now(),passed,reports,reusedEvidence,missingDimensions:uniqueMissing}},'QUALITY_CERTIFIED',root);return {passed,profile,evidence,reports,reusedEvidence,missingDimensions:uniqueMissing,reason:passed?null:evidence.find(e=>e.status==='failed')?.stderr||`missing required quality evidence: ${uniqueMissing.join(', ')}`};
}
