import path from 'node:path';import { id,run } from './utils.js';import { executeProcess } from './runtime.js';import { paths } from './store.js';
const q=s=>`'${String(s).replaceAll("'","'\\''")}'`;
const CONTROL_TIMEOUT_MS=15000,SYNC_TIMEOUT_MS=5*60*1000,REMOTE_BUFFER=8*1024*1024;
const sshArgs=(host,command,connectTimeout=5)=>['-o','BatchMode=yes','-o',`ConnectTimeout=${connectTimeout}`,host,command];
function bounded(cmd,args,{timeout=CONTROL_TIMEOUT_MS,maxBuffer=REMOTE_BUFFER,cwd}={}){const r=run(cmd,args,{cwd,timeout:Math.max(1000,Number(timeout)||CONTROL_TIMEOUT_MS),maxBuffer:Math.max(64*1024,Number(maxBuffer)||REMOTE_BUFFER)});if(r.error?.code==='ETIMEDOUT')return {...r,status:r.status??1,timedOut:true,stderr:(r.stderr||'')||`${cmd} timed out after ${timeout}ms`};return {...r,timedOut:false};}
function must(result,label){if(result.timedOut)throw new Error(`${label} timed out`);if(result.status!==0)throw new Error(`${label} failed: ${result.stderr||result.stdout||'unknown error'}`);return result;}
export function sshAvailable(){return bounded('ssh',['-V'],{timeout:5000,maxBuffer:1024*1024}).status===0;}
export function rsyncAvailable(){return bounded('rsync',['--version'],{timeout:5000,maxBuffer:1024*1024}).status===0;}
export function remoteDoctor(host,{timeoutMs=CONTROL_TIMEOUT_MS}={}){const r=bounded('ssh',sshArgs(host,'node --version && git --version && (uname -s 2>/dev/null || ver)'),{timeout:timeoutMs});return {host,available:r.status===0&&!r.timedOut,rsync:rsyncAvailable(),timedOut:r.timedOut,output:(r.stdout||r.stderr||'').trim()};}
export function remoteExec(host,command,{cwd,timeoutMs=60000}={}){const remote=cwd?`cd ${q(cwd)} && ${command}`:command,r=bounded('ssh',sshArgs(host,remote),{timeout:timeoutMs});return {exitCode:r.status??1,stdout:r.stdout||'',stderr:r.stderr||'',timedOut:r.timedOut};}
export function remoteVerify(host,worktree,commands){if(!sshAvailable())throw new Error('ssh executable not available');if(!rsyncAvailable())throw new Error('rsync is required for remote verification');const mk=must(bounded('ssh',sshArgs(host,'mktemp -d /tmp/shipstate-verify-XXXXXX'),{timeout:CONTROL_TIMEOUT_MS}),'remote temp');const remoteDir=(mk.stdout||'').trim();try{must(bounded('rsync',['-az','--delete','--exclude','.git/',`${worktree.replace(/\/$/,'')}/`,`${host}:${remoteDir}/`],{timeout:SYNC_TIMEOUT_MS}),'remote verification upload');const results=[];for(const command of commands){const r=remoteExec(host,command,{cwd:remoteDir,timeoutMs:15*60*1000});results.push({command,...r});if(r.timedOut)break;}return {host,remoteDir,results};}finally{bounded('ssh',sshArgs(host,`rm -rf ${q(remoteDir)}`),{timeout:CONTROL_TIMEOUT_MS});}}
export async function remoteExecuteWorktree({host,worktree,command,contextFile=null,root=process.cwd(),timeoutMs=30*60*1000,runId=id('remote'),logPath=path.join(paths(root).runs,`${runId}.remote.log`),syncBack=true,heartbeatSeconds=20}){if(!host)throw new Error('remote host is required');const d=remoteDoctor(host);if(!d.available)throw new Error(`remote host unavailable: ${host}${d.timedOut?' (doctor timed out)':''}`);if(!d.rsync)throw new Error('rsync is required for remote execution');const mk=must(bounded('ssh',sshArgs(host,'mktemp -d /tmp/shipstate-run-XXXXXX'),{timeout:CONTROL_TIMEOUT_MS}),'remote temp');const remoteDir=(mk.stdout||'').trim(),startedAt=new Date().toISOString(),heartbeats=[];try{must(bounded('rsync',['-az','--delete','--exclude','.git/','--exclude','.shipstate/',`${worktree.replace(/\/$/,'')}/`,`${host}:${remoteDir}/`],{timeout:SYNC_TIMEOUT_MS}),'remote upload');let remoteContext=null;if(contextFile){remoteContext=`${remoteDir}/.shipstate-context.md`;must(bounded('rsync',['-az',contextFile,`${host}:${remoteContext}`],{timeout:SYNC_TIMEOUT_MS}),'remote context upload');}const hb=`${remoteDir}/.shipstate-heartbeat`,resolvedCommand=String(command||'').replaceAll('{CONTEXT}',remoteContext||`${remoteDir}/.shipstate-context.md`),wrapped=`cd ${q(remoteDir)} && trap 'rm -f ${q(hb)} ${remoteContext?q(remoteContext):''}' EXIT HUP INT TERM; (while true; do date +%s > ${q(hb)}; sleep ${Math.max(5,Number(heartbeatSeconds)||20)}; done) & HB=$!; trap 'kill $HB 2>/dev/null; rm -f ${q(hb)} ${remoteContext?q(remoteContext):''}' EXIT HUP INT TERM; ${resolvedCommand}; RC=$?; kill $HB 2>/dev/null; wait $HB 2>/dev/null; exit $RC`;const timer=setInterval(()=>{const h=bounded('ssh',sshArgs(host,`cat ${q(hb)} 2>/dev/null || true`,3),{timeout:5000,maxBuffer:1024*1024});if(h.status===0&&!h.timedOut&&(h.stdout||'').trim())heartbeats.push({at:new Date().toISOString(),remoteEpoch:Number((h.stdout||'').trim())||null});},Math.max(5000,(Number(heartbeatSeconds)||20)*1000));let result;try{result=await executeProcess({runId,cmd:'ssh',args:sshArgs(host,wrapped),cwd:root,env:process.env,timeoutMs,logPath});}finally{clearInterval(timer);}let download=null;if(syncBack){download=must(bounded('rsync',['-az','--delete','--exclude','.git/','--exclude','.shipstate/','--exclude','.shipstate-heartbeat','--exclude','.shipstate-context.md',`${host}:${remoteDir}/`,`${worktree.replace(/\/$/,'')}/`],{timeout:SYNC_TIMEOUT_MS}),'remote artifact sync');}return {runId,host,remoteDir,startedAt,completedAt:new Date().toISOString(),heartbeats,result,syncBack,downloadExitCode:download?.status??null};}finally{bounded('ssh',sshArgs(host,`rm -rf ${q(remoteDir)}`),{timeout:CONTROL_TIMEOUT_MS});}}
