import fs from 'node:fs';import path from 'node:path';import { id,now,sha256 } from './utils.js';import { readState,transition,recordRun,recordMetric,paths } from './store.js';import { eligible } from './core.js';import { compileContext } from './context.js';import { compileRoutedContext } from './context-router.js';import { head,isClean,worktreeFor,changedFiles,removeWorktree } from './git.js';import { commandFor,authStatus,requiresMacKeychain } from './agents.js';import { sandboxCommand,sanitizedEnv,detectSandbox } from './sandbox.js';import { executeProcess,cancelRun as cancelActive } from './runtime.js';
function fingerprint(text){return sha256((text||'').replace(/\d+/g,'#').replace(/\/[^\s:]+/g,'<path>')).slice(0,16);}
async function executionContext(taskId,root,opts){return fs.existsSync(path.join(root,'shipstate.project.json'))?compileRoutedContext(taskId,root,opts):compileContext(taskId,root,opts);}
export async function runTask(taskId,agent='manual',root=process.cwd(),opts={}){
 const s=readState(root);const task=s.tasks.find(t=>t.id===taskId);if(!task)throw new Error(`Unknown task: ${taskId}`);const by=Object.fromEntries(s.tasks.map(t=>[t.id,t]));if(!eligible(task,by)&&task.state!=='READY')throw new Error(`Task ${taskId} is not eligible; dependencies must be ACCEPTED`);if(!isClean(root))throw new Error('Main working tree must be clean before execution');
 const hostAuth=authStatus(agent);if(hostAuth.supported&&hostAuth.loggedIn===false)throw new Error(`${agent} is not authenticated on the host. Authenticate the CLI before running SHIPSTATE.`);
 if(['PENDING','FAILED','REJECTED','BLOCKED'].includes(task.state))transition(taskId,'READY',{},root);transition(taskId,'RUNNING',{lastAgent:agent},root);
 const runId=id('run');const base=head(root);const wt=worktreeFor(taskId,runId,base,root);let ctx;try{ctx=await executionContext(taskId,root,opts);}catch(e){removeWorktree(wt,root);transition(taskId,'FAILED',{lastRunId:null,blockedReason:'context_compilation_failed',contextError:e.message},root);throw e;}const contextPath=ctx.path;const logPath=path.join(paths(root).runs,`${runId}.log`);const timeoutMs=Number(opts.timeoutMs||task.timeoutMs||s.project.timeoutMs||30*60*1000);const descriptor=detectSandbox();const runRec={id:runId,taskId,agent,status:'running',baseCommit:base,worktreePath:wt,contextHash:ctx.hash,contextTokens:ctx.tokens,contextReceiptPath:ctx.receiptPath||null,contextProvider:ctx.receipt?.providers?.structural?.id||'shipstate-lite',startedAt:now(),timeoutMs,logPath,sandbox:descriptor,hostAuth};recordRun(runRec,root);
 if(agent==='manual'){runRec.status='awaiting_manual';runRec.completedAt=now();recordRun(runRec,root);transition(taskId,'IMPLEMENTED',{lastRunId:runId,manualPending:true},root);return runRec;}
 const baseSpec=commandFor(agent,contextPath);const network=task.network!==undefined?Boolean(task.network):['claude','codex'].includes(agent);const keychainAccess=process.platform==='darwin'&&requiresMacKeychain(agent)&&hostAuth.loggedIn===true;const spec=sandboxCommand(baseSpec,{worktree:wt,network,memoryMb:Number(task.memoryMb||s.project.memoryMb||0),cpuSeconds:Number(task.cpuSeconds||s.project.cpuSeconds||0),keychainAccess});runRec.sandbox=spec.descriptor;recordRun(runRec,root);const result=await executeProcess({runId,cmd:spec.cmd,args:spec.args,cwd:wt,env:sanitizedEnv(),timeoutMs,logPath});runRec.completedAt=now();runRec.exitCode=result.exitCode;runRec.timedOut=result.timedOut;runRec.cancelled=result.cancelled;runRec.changedFiles=changedFiles(wt);runRec.status=result.exitCode===0&&!result.timedOut&&!result.cancelled?'passed':'failed';runRec.failureFingerprint=runRec.status==='failed'?fingerprint(`${result.stderr}\n${result.stdout}`):null;runRec.stdoutTail=result.stdout.slice(-4000);runRec.stderrTail=result.stderr.slice(-4000);if(runRec.status==='failed'&&hostAuth.loggedIn===true&&/not logged in|please run \/login/i.test(`${result.stdout}\n${result.stderr}`))runRec.authFailure='sandbox_credential_access';recordRun(runRec,root);recordMetric('agentRuns',{at:now(),taskId,runId,agent,status:runRec.status,contextTokens:ctx.tokens,contextProvider:runRec.contextProvider,durationMs:Date.parse(runRec.completedAt)-Date.parse(runRec.startedAt),changedFiles:runRec.changedFiles.length},root);
 if(runRec.status==='passed')transition(taskId,'IMPLEMENTED',{lastRunId:runId,manualPending:false},root);else{const after=readState(root);const repeats=after.runs.filter(r=>r.taskId===taskId&&r.failureFingerprint&&r.failureFingerprint===runRec.failureFingerprint).length;transition(taskId,repeats>=3?'BLOCKED':'FAILED',{lastRunId:runId,blockedReason:repeats>=3?'repeated_failure':runRec.timedOut?'timeout':runRec.cancelled?'cancelled':runRec.authFailure||null},root);if(!opts.keepFailedWorktree)removeWorktree(wt,root);}return runRec;
}
export function cancelRun(runId,root=process.cwd()){const ok=cancelActive(runId);if(ok)return true;const s=readState(root);const r=s.runs.find(x=>x.id===runId);if(!r)return false;return false;}
