import fs from 'node:fs';import path from 'node:path';import { id,now,sha256 } from './utils.js';import { readState,transition,recordRun,recordMetric,paths } from './store.js';import { eligible,depsAccepted } from './core.js';import { compileContext } from './context.js';import { compileRoutedContext } from './context-router.js';import { head,isClean,worktreeFor,changedFiles,removeWorktree } from './git.js';import { commandFor,authStatus,requiresMacKeychain } from './agents.js';import { sandboxCommand,sanitizedEnv,detectSandbox } from './sandbox.js';import { executeProcess,cancelRun as cancelActive } from './runtime.js';import { remoteExecuteWorktree,remoteDoctor } from './remote.js';
function fingerprint(text){return sha256((text||'').replace(/\d+/g,'#').replace(/\/[^\s:]+/g,'<path>')).slice(0,16);}
export function classifyProviderAvailability({stdout='',stderr='',changedFiles=[]}={}){if((changedFiles||[]).length)return null;const text=`${stderr}\n${stdout}`;if(/(?:you(?:'|’)ve hit your session limit|session limit(?: reached| exceeded)?|usage limit(?: reached| exceeded)?|quota (?:exceeded|exhausted)|insufficient quota|credit balance (?:is )?(?:too low|exhausted)|rate limit exceeded|too many requests)/i.test(text))return 'provider_quota';if(/(?:not logged in|please run \/login|authentication required|auth required|login required|credentials? (?:missing|expired|unavailable))/i.test(text))return 'provider_auth';if(/(?:\bENOENT\b|command not found|executable (?:not found|missing|unavailable)|blocked on a permissions? prompt|permission(?:s)? (?:prompt|approval).*(?:not|hasn.t) (?:been )?(?:granted|approved)|approve (?:the )?(?:file[- ]write )?permission|blocked by .*read-only filesystem|requires a writable session|read-only.*no files were changed|path is outside allowed working directories|context(?: file| path)?.*(?:outside.*allowed|inaccessible|unreadable|access denied|auto-denied)|(?:hard blocker|can.t proceed safely).*(?:context|task instructions))/i.test(text))return 'provider_unavailable';return null;}
async function executionContext(taskId,root,opts){return fs.existsSync(path.join(root,'shipstate.project.json'))?compileRoutedContext(taskId,root,opts):compileContext(taskId,root,opts);}
const sq=s=>`'${String(s).replaceAll("'","'\\''")}'`;
function remoteCommandFor(agent){const spec=commandFor(agent,'{CONTEXT}');if(!spec)return null;const cmd=spec.cmd===process.execPath?'node':spec.cmd;return [cmd,...spec.args].map(sq).join(' ');}
export async function runTask(taskId,agent='manual',root=process.cwd(),opts={}){
 const s=readState(root);const task=s.tasks.find(t=>t.id===taskId);if(!task)throw new Error(`Unknown task: ${taskId}`);const by=Object.fromEntries(s.tasks.map(t=>[t.id,t]));const explicitRetry=['FAILED','REJECTED','BLOCKED'].includes(task.state)&&depsAccepted(task,by);if(!eligible(task,by)&&task.state!=='READY'&&!explicitRetry)throw new Error(`Task ${taskId} is not eligible; dependencies must be ACCEPTED`);if(!isClean(root))throw new Error('Main working tree must be clean before execution');const remoteHost=opts.remoteHost||task.remoteHost||null;
 const hostAuth=remoteHost?{supported:false,loggedIn:null,authMethod:'remote-host',status:null}:authStatus(agent);if(hostAuth.supported&&hostAuth.loggedIn===false)throw new Error(`${agent} is not authenticated on the host. Authenticate the CLI before running SHIPSTATE.`);if(remoteHost&&!remoteDoctor(remoteHost).available)throw new Error(`Remote execution host is unavailable: ${remoteHost}`);
 if(['PENDING','FAILED','REJECTED','BLOCKED'].includes(task.state))transition(taskId,'READY',{},root);transition(taskId,'RUNNING',{lastAgent:agent,remoteHost,blockedReason:null,contextError:null},root);const runId=id('run'),base=head(root),wt=worktreeFor(taskId,runId,base,root);let ctx;try{ctx=await executionContext(taskId,root,opts);}catch(e){removeWorktree(wt,root);transition(taskId,'FAILED',{lastRunId:null,blockedReason:'context_compilation_failed',contextError:e.message},root);throw e;}const contextPath=ctx.path,logPath=path.join(paths(root).runs,`${runId}.log`),timeoutMs=Number(opts.timeoutMs||task.timeoutMs||s.project.timeoutMs||30*60*1000),descriptor=remoteHost?{kind:'remote-ssh',level:'remote',available:true,host:remoteHost,warning:'Remote isolation is host-defined; SHIPSTATE still enforces worktree/diff policy after sync-back.'}:detectSandbox(),runRec={id:runId,taskId,agent,status:'running',baseCommit:base,worktreePath:wt,contextHash:ctx.hash,contextTokens:ctx.tokens,contextReceiptPath:ctx.receiptPath||null,contextProvider:ctx.receipt?.providers?.structural?.id||'shipstate-lite',startedAt:now(),timeoutMs,logPath,sandbox:descriptor,hostAuth,remoteHost};recordRun(runRec,root);
 if(agent==='manual'){runRec.status='awaiting_manual';runRec.completedAt=now();recordRun(runRec,root);transition(taskId,'IMPLEMENTED',{lastRunId:runId,manualPending:true},root);return runRec;}
 let localContextPath=null,contextHashBefore=null;if(!remoteHost){localContextPath=path.join(wt,'.shipstate-context.md');fs.copyFileSync(contextPath,localContextPath);contextHashBefore=sha256(fs.readFileSync(localContextPath));}
 let result;if(remoteHost){const remote=await remoteExecuteWorktree({host:remoteHost,worktree:wt,command:remoteCommandFor(agent),contextFile:contextPath,root,timeoutMs,runId,logPath,syncBack:true});runRec.remote={host:remoteHost,heartbeats:remote.heartbeats.length,startedAt:remote.startedAt,completedAt:remote.completedAt};result=remote.result;runRec.sandbox={...descriptor,remoteHeartbeats:remote.heartbeats.length};}else{const baseSpec=commandFor(agent,localContextPath||contextPath),network=task.network!==undefined?Boolean(task.network):['claude','codex'].includes(agent),keychainAccess=process.platform==='darwin'&&requiresMacKeychain(agent)&&hostAuth.loggedIn===true,spec=sandboxCommand(baseSpec,{worktree:wt,network,memoryMb:Number(task.memoryMb||s.project.memoryMb||0),cpuSeconds:Number(task.cpuSeconds||s.project.cpuSeconds||0),keychainAccess});runRec.sandbox=spec.descriptor;recordRun(runRec,root);result=await executeProcess({runId,cmd:spec.cmd,args:spec.args,cwd:wt,env:sanitizedEnv(),timeoutMs,logPath});}
 runRec.completedAt=now();runRec.exitCode=result.exitCode;runRec.timedOut=result.timedOut;runRec.cancelled=result.cancelled;let contextTampered=false;if(localContextPath&&fs.existsSync(localContextPath)){contextTampered=sha256(fs.readFileSync(localContextPath))!==contextHashBefore;fs.rmSync(localContextPath,{force:true});}runRec.changedFiles=changedFiles(wt);runRec.contextTampered=contextTampered;runRec.providerAvailability=contextTampered?null:classifyProviderAvailability({stdout:result.stdout,stderr:result.stderr,changedFiles:runRec.changedFiles});runRec.status=result.exitCode===0&&!result.timedOut&&!result.cancelled&&!runRec.providerAvailability&&!contextTampered?'passed':'failed';runRec.failureFingerprint=runRec.status==='failed'?fingerprint(`${result.stderr}\n${result.stdout}`):null;runRec.stdoutTail=result.stdout.slice(-4000);runRec.stderrTail=result.stderr.slice(-4000);if(!remoteHost&&runRec.status==='failed'&&hostAuth.loggedIn===true&&/not logged in|please run \/login/i.test(`${result.stdout}\n${result.stderr}`))runRec.authFailure='sandbox_credential_access';recordRun(runRec,root);recordMetric('agentRuns',{at:now(),taskId,runId,agent,status:runRec.status,contextTokens:ctx.tokens,contextProvider:runRec.contextProvider,durationMs:Date.parse(runRec.completedAt)-Date.parse(runRec.startedAt),changedFiles:runRec.changedFiles.length,remoteHost,providerAvailability:runRec.providerAvailability},root);if(runRec.status==='passed')transition(taskId,'IMPLEMENTED',{lastRunId:runId,manualPending:false},root);else{const after=readState(root),repeats=after.runs.filter(r=>r.taskId===taskId&&r.failureFingerprint&&r.failureFingerprint===runRec.failureFingerprint).length;transition(taskId,repeats>=3?'BLOCKED':'FAILED',{lastRunId:runId,blockedReason:contextTampered?'context_tampered':runRec.providerAvailability|| (repeats>=3?'repeated_failure':runRec.timedOut?'timeout':runRec.cancelled?'cancelled':runRec.authFailure||null)},root);if(!opts.keepFailedWorktree)removeWorktree(wt,root);}return runRec;
}
export function cancelRun(runId,root=process.cwd()){const ok=cancelActive(runId);if(ok)return true;const s=readState(root);const r=s.runs.find(x=>x.id===runId);if(!r)return false;return false;}
