import { readState,recordDecision } from './store.js';import { chooseNext,eligible } from './core.js';import { runTask } from './runner.js';import { verifyTask } from './verifier.js';import { acceptTask } from './actions.js';import { id,now,matchGlob } from './utils.js';
function patternsOverlap(a,b){if(!a.length||!b.length)return true;for(const x of a)for(const y of b){const px=x.replace('/**',''),py=y.replace('/**','');if(px.startsWith(py)||py.startsWith(px)||x===y)return true;}return false;}
export function independentBatch(tasks,limit=2){const by=Object.fromEntries(tasks.map(t=>[t.id,t]));const eligibleTasks=tasks.filter(t=>eligible(t,by)).sort((a,b)=>(b.priority||0)-(a.priority||0));const batch=[];for(const t of eligibleTasks){if(batch.length>=limit)break;if(batch.every(x=>!patternsOverlap(x.allowedPaths||[],t.allowedPaths||[])))batch.push(t);}return batch;}
export async function executeOne(task,agent,root,opts={}){let run=await runTask(task.id,agent,root,opts);if(agent==='manual')return {taskId:task.id,run,manual:true};if(run.status!=='passed')return {taskId:task.id,run,verified:false};const verification=verifyTask(task.id,root);if(!verification.passed)return {taskId:task.id,run,verification,verified:false};const state=readState(root);const current=state.tasks.find(t=>t.id===task.id);const auto=(state.project.autoAcceptRisk||[]).includes(current.risk||'medium')&&opts.autoAccept!==false;let acceptance=null;if(auto)acceptance=acceptTask(task.id,root,'autopilot');return {taskId:task.id,run,verification,acceptance,verified:true};}
export async function autopilot({agent=null,maxTasks=10,parallel=1,maxAttempts=2,autoAccept=true}={},root=process.cwd()){
 const results=[];let processed=0;while(processed<maxTasks){const s=readState(root);const selected=parallel>1?independentBatch(s.tasks,parallel):[chooseNext(s.tasks)].filter(Boolean);if(!selected.length)break;
  if(parallel>1){const outs=await Promise.all(selected.map(t=>executeOne(t,agent||s.project.defaultAgent||'manual',root,{autoAccept:false})));if(autoAccept&&!outs.some(x=>x.manual)){for(const out of outs){if(!out.verified)continue;const current=readState(root).tasks.find(t=>t.id===out.taskId);if(!(readState(root).project.autoAcceptRisk||[]).includes(current?.risk||'medium'))continue;try{out.acceptance=acceptTask(out.taskId,root,'autopilot',{allowDisjointStale:true,postVerify:true});}catch(e){out.acceptanceError=e.message;}}}results.push(...outs);processed+=outs.length;if(outs.some(x=>x.manual))break;
  }else{const t=selected[0];let out=null;for(let attempt=0;attempt<maxAttempts;attempt++){out=await executeOne(t,agent||s.project.defaultAgent||'manual',root,{autoAccept});if(out.manual||out.verified)break;}results.push(out);processed++;if(out?.manual)break;}
 }
 recordDecision({id:id('decision'),type:'autopilot-run',actor:'system',at:now(),processed,parallel,results:results.map(r=>({taskId:r.taskId,verified:r.verified||false,accepted:Boolean(r.acceptance),manual:Boolean(r.manual)}))},root);return {processed,results};
}
