import fs from 'node:fs'; import path from 'node:path';
import { id,now,sha256,ensureDir,readJson,writeJsonAtomic } from './utils.js'; import { assertTransition } from './core.js'; import { detectProject } from './profile.js';
export const CURRENT_SCHEMA=5;
export function paths(root=process.cwd()){const base=path.join(root,'.shipstate');return {base,state:path.join(base,'state.json'),prev:path.join(base,'state.prev.json'),events:path.join(base,'events.jsonl'),runs:path.join(base,'runs'),contexts:path.join(base,'contexts'),worktrees:path.join(base,'worktrees'),locks:path.join(base,'locks.json'),profiles:path.join(base,'profile.json'),backups:path.join(base,'backups'),cache:path.join(base,'cache'),advisories:path.join(base,'advisories')};}
export const initialized=(root=process.cwd())=>fs.existsSync(paths(root).state);
function ensureJournalFormat(root){const f=paths(root).events;if(!fs.existsSync(f))return;const lines=fs.readFileSync(f,'utf8').split(/\n/).filter(Boolean);if(!lines.length)return;let parsed;try{parsed=lines.map(JSON.parse);}catch{return;}if(parsed.every(e=>e.hash&&e.prevHash))return;ensureDir(paths(root).backups);fs.copyFileSync(f,path.join(paths(root).backups,`events-legacy-${Date.now()}.jsonl`));let prev='GENESIS';const out=[];for(const old of parsed){const base={id:old.id||id('evt'),type:old.type||'LEGACY_EVENT',at:old.at||now(),payload:old.payload||old,prevHash:prev};const event={...base,hash:sha256(JSON.stringify(base))};out.push(JSON.stringify(event));prev=event.hash;}fs.writeFileSync(f,out.join('\n')+'\n');}
function autonomousDefaults(){return {handover:{status:'DRAFT',contractHash:null},delivery:{state:'PROJECT_SETUP',planBootstrapped:false,authorizedGates:{}},team:{manager:'codex',reviewer:'codex',developer:'claude',verifier:'shipstate'},ownerDecisions:[],intelligence:{projectTruth:null,providers:{},quality:{}},repairEpisodes:[]};}
function emptyState(root,name){return {schemaVersion:CURRENT_SCHEMA,project:{id:id('project'),name:name||path.basename(root),createdAt:now(),allowedPaths:[],protectedPaths:[],defaultAgent:'manual',autoAcceptRisk:['low']},profile:detectProject(root),tasks:[],runs:[],evidence:[],decisions:[],metrics:{contexts:[],agentRuns:[],projectTruth:[],providers:[],tokenEconomy:[]},locks:[],plans:[],remotes:[],...autonomousDefaults()};}
function migrate(s){let out=structuredClone(s||{});let v=Number(out.schemaVersion||1);if(v<2){out.decisions||=[];out.metrics||={contexts:[],agentRuns:[]};out.locks||=[];out.plans||=[];v=2;}if(v<3){out.profile||={};out.remotes||=[];out.project||={};out.project.autoAcceptRisk||=['low'];v=3;}if(v<4){const d=autonomousDefaults();out.handover||=d.handover;out.delivery||=d.delivery;out.team||=d.team;out.ownerDecisions||=[];v=4;}if(v<5){const d=autonomousDefaults();out.intelligence||=d.intelligence;out.repairEpisodes||=[];out.metrics||={};out.metrics.projectTruth||=[];out.metrics.providers||=[];out.metrics.tokenEconomy||=[];v=5;}out.delivery={...autonomousDefaults().delivery,...(out.delivery||{}),authorizedGates:{...(out.delivery?.authorizedGates||{})}};out.handover={...autonomousDefaults().handover,...(out.handover||{})};out.team={...autonomousDefaults().team,...(out.team||{})};out.ownerDecisions||=[];out.intelligence={...autonomousDefaults().intelligence,...(out.intelligence||{}),providers:{...(out.intelligence?.providers||{})},quality:{...(out.intelligence?.quality||{})}};out.repairEpisodes||=[];out.metrics={contexts:[],agentRuns:[],projectTruth:[],providers:[],tokenEconomy:[],...(out.metrics||{})};out.schemaVersion=CURRENT_SCHEMA;return out;}
export function initStore(root=process.cwd(),name){const p=paths(root);for(const d of [p.base,p.runs,p.contexts,p.worktrees,p.backups,p.cache,p.advisories])ensureDir(d);if(!fs.existsSync(p.state))writeJsonAtomic(p.state,emptyState(root,name));if(!fs.existsSync(p.events))fs.writeFileSync(p.events,'');ensureJournalFormat(root);appendEvent('PROJECT_INITIALIZED',{root,project:readJson(p.state)?.project,profile:readJson(p.state)?.profile,schemaVersion:CURRENT_SCHEMA},root);ensureGitignore(root);return readState(root);}
function ensureGitignore(root){const f=path.join(root,'.gitignore');let t=fs.existsSync(f)?fs.readFileSync(f,'utf8'):'';if(!t.split(/\r?\n/).includes('.shipstate/')){if(t&&!t.endsWith('\n'))t+='\n';fs.writeFileSync(f,t+'.shipstate/\n');}}
export function readState(root=process.cwd()){ensureJournalFormat(root);const p=paths(root);let raw=readJson(p.state);if(!raw&&fs.existsSync(p.prev)){raw=readJson(p.prev);if(raw)writeJsonAtomic(p.state,raw);}if(!raw)throw new Error('SHIPSTATE state missing or invalid; no last-good snapshot available');const s=migrate(raw);if(s.schemaVersion!==raw.schemaVersion)writeState(s,root);return s;}
export function writeState(s,root=process.cwd()){s.schemaVersion=CURRENT_SCHEMA;const p=paths(root);if(fs.existsSync(p.state)){try{fs.copyFileSync(p.state,p.prev);}catch{}}writeJsonAtomic(p.state,s);}
function lastEventHash(root){try{const lines=fs.readFileSync(paths(root).events,'utf8').trim().split(/\n/).filter(Boolean);if(!lines.length)return 'GENESIS';return JSON.parse(lines.at(-1)).hash||'GENESIS';}catch{return 'GENESIS';}}
export function appendEvent(type,payload,root=process.cwd()){ensureJournalFormat(root);const prevHash=lastEventHash(root);const base={id:id('evt'),type,at:now(),payload,prevHash};const event={...base,hash:sha256(JSON.stringify(base))};ensureDir(paths(root).base);fs.appendFileSync(paths(root).events,JSON.stringify(event)+'\n');return event;}
export function verifyJournal(root=process.cwd()){if(!fs.existsSync(paths(root).events))return {valid:true,count:0};let prev='GENESIS',count=0;for(const line of fs.readFileSync(paths(root).events,'utf8').split(/\n/).filter(Boolean)){const e=JSON.parse(line);const {hash,...base}=e;if(e.prevHash!==prev||sha256(JSON.stringify(base))!==hash)return {valid:false,count,error:`broken event chain at ${e.id}`};prev=hash;count++;}return {valid:true,count,lastHash:prev};}
export function backupState(root=process.cwd()){const p=paths(root);ensureDir(p.backups);const out=path.join(p.backups,`state-${Date.now()}.json`);fs.copyFileSync(p.state,out);return out;}
export function refreshProfile(root=process.cwd()){const s=readState(root);s.profile=detectProject(root);appendEvent('PROFILE_REFRESHED',{profile:s.profile},root);writeState(s,root);return s.profile;}
export function addTasks(tasks,root=process.cwd()){const s=readState(root);const ids=new Set(s.tasks.map(t=>t.id));for(const raw of tasks){const t={...raw};if(ids.has(t.id))throw new Error(`Duplicate task: ${t.id}`);ids.add(t.id);if(!(t.verification||[]).length)t.verification=[s.profile?.commands?.test,s.profile?.commands?.typecheck,s.profile?.commands?.lint].filter(Boolean);if(!(t.allowedPaths||[]).length)t.allowedPaths=[...(s.profile?.sourceDirs||[]).map(x=>`${x}/**`),...(s.profile?.testDirs||[]).filter(Boolean).map(x=>`${x}/**`)];s.tasks.push(t);appendEvent('TASK_IMPORTED',{task:t},root);}writeState(s,root);return s;}
export function transition(taskId,to,meta={},root=process.cwd()){const s=readState(root);const t=s.tasks.find(x=>x.id===taskId);if(!t)throw new Error(`Unknown task: ${taskId}`);assertTransition(t.state,to);const from=t.state;t.state=to;t.updatedAt=now();Object.assign(t,meta);appendEvent('TASK_TRANSITION',{taskId,from,to,meta},root);writeState(s,root);return t;}
export function mutateTask(taskId,patch,event='TASK_UPDATED',root=process.cwd()){const s=readState(root);const t=s.tasks.find(x=>x.id===taskId);if(!t)throw new Error(`Unknown task: ${taskId}`);Object.assign(t,patch,{updatedAt:now()});appendEvent(event,{taskId,patch},root);writeState(s,root);return t;}
export function recordRun(run,root=process.cwd()){const s=readState(root);const i=s.runs.findIndex(r=>r.id===run.id);if(i>=0)s.runs[i]=run;else s.runs.push(run);appendEvent('RUN_RECORDED',{run},root);writeState(s,root);return run;}
export function recordEvidence(items,root=process.cwd()){const s=readState(root);s.evidence.push(...items);for(const e of items)appendEvent('EVIDENCE_RECORDED',{evidence:e},root);writeState(s,root);return items;}
export function recordDecision(decision,root=process.cwd()){const s=readState(root);s.decisions.push(decision);appendEvent('DECISION_RECORDED',decision,root);writeState(s,root);return decision;}
export function recordMetric(kind,item,root=process.cwd()){const s=readState(root);s.metrics[kind]||=[];s.metrics[kind].push(item);appendEvent('METRIC_RECORDED',{kind,item},root);writeState(s,root);return item;}
export function recordIntelligence(patch,event='INTELLIGENCE_UPDATED',root=process.cwd()){const s=readState(root);s.intelligence={...(s.intelligence||{}),...patch,providers:{...(s.intelligence?.providers||{}),...(patch.providers||{})},quality:{...(s.intelligence?.quality||{}),...(patch.quality||{})}};appendEvent(event,{patch},root);writeState(s,root);return s.intelligence;}
export function recordRepairEpisode(episode,root=process.cwd()){const s=readState(root);const i=s.repairEpisodes.findIndex(x=>x.id===episode.id);if(i>=0)s.repairEpisodes[i]=episode;else s.repairEpisodes.push(episode);appendEvent('REPAIR_EPISODE_RECORDED',{episode},root);writeState(s,root);return episode;}
export function setLocks(locks,root=process.cwd()){const s=readState(root);s.locks=locks;appendEvent('DESIGN_LOCKS_UPDATED',{count:locks.length,locks},root);writeState(s,root);return locks;}
export function addPlan(plan,root=process.cwd()){const s=readState(root);s.plans.push(plan);appendEvent('PLAN_CREATED',{plan},root);writeState(s,root);return plan;}
export function rebuildFromSnapshot(root=process.cwd()){const j=verifyJournal(root);if(!j.valid)throw new Error(j.error);return {ok:true,journal:j,state:readState(root)};}
export function replayStateFromJournal(root=process.cwd()){
 ensureJournalFormat(root);const p=paths(root);const lines=fs.readFileSync(p.events,'utf8').split(/\n/).filter(Boolean).map(JSON.parse);let state=null;for(const e of lines){const q=e.payload||{};if(e.type==='PROJECT_INITIALIZED'&&q.project)state={schemaVersion:CURRENT_SCHEMA,project:q.project,profile:q.profile||{},tasks:[],runs:[],evidence:[],decisions:[],metrics:{contexts:[],agentRuns:[],projectTruth:[],providers:[],tokenEconomy:[]},locks:[],plans:[],remotes:[],...autonomousDefaults()};if(!state)continue;if(e.type==='TASK_IMPORTED'&&q.task&&!state.tasks.some(t=>t.id===q.task.id))state.tasks.push(q.task);else if(e.type==='TASK_TRANSITION'){const t=state.tasks.find(t=>t.id===q.taskId);if(t){t.state=q.to;Object.assign(t,q.meta||{});}}else if(e.type==='RUN_RECORDED'&&q.run){const i=state.runs.findIndex(r=>r.id===q.run.id);if(i>=0)state.runs[i]=q.run;else state.runs.push(q.run);}else if(e.type==='EVIDENCE_RECORDED'&&q.evidence)state.evidence.push(q.evidence);else if(e.type==='DECISION_RECORDED')state.decisions.push(q);else if(e.type==='PROFILE_REFRESHED')state.profile=q.profile||state.profile;else if(e.type==='DESIGN_LOCKS_UPDATED'&&q.locks)state.locks=q.locks;else if(e.type==='PLAN_CREATED'&&q.plan)state.plans.push(q.plan);else if(e.type==='PLAN_APPROVED'){const pl=state.plans.find(x=>x.id===q.planId);if(pl)pl.status='APPROVED';}else if(e.type==='METRIC_RECORDED'){state.metrics[q.kind]||=[];state.metrics[q.kind].push(q.item);}else if(e.type==='HANDOVER_INITIALIZED')state.handover={...(state.handover||{}),status:'HANDOVER_REVIEW'};else if(e.type==='HANDOVER_ACCEPTED')state.handover={...(state.handover||{}),status:'READY_FOR_HANDOVER',contractHash:q.contractHash,roles:q.roles,autonomy:q.autonomy};else if(e.type==='PROJECT_HANDED_OVER')state.handover={...(state.handover||{}),status:'HANDED_OVER'};else if(e.type==='PROJECT_LIFECYCLE')state.delivery={...(state.delivery||{}),...(q.patch||{}),state:q.state};else if(e.type==='OWNER_DECISION_OPENED'&&q.decision)state.ownerDecisions.push(q.decision);else if(e.type==='OWNER_DECISION_RESOLVED'){const d=state.ownerDecisions.find(x=>x.id===q.decisionId);if(d){d.status='RESOLVED';d.resolution=q.resolution;d.note=q.note;}}else if(e.type==='INTELLIGENCE_UPDATED')state.intelligence={...(state.intelligence||{}),...(q.patch||{})};else if(e.type==='REPAIR_EPISODE_RECORDED'&&q.episode){const i=state.repairEpisodes.findIndex(x=>x.id===q.episode.id);if(i>=0)state.repairEpisodes[i]=q.episode;else state.repairEpisodes.push(q.episode);}}
 if(!state)throw new Error('Journal does not contain replayable project initialization');writeState(state,root);appendEvent('STATE_REPLAYED',{eventCount:lines.length},root);return state;
}
