import { readState,transition,recordEvidence,recordRun,mutateTask } from './store.js';import { changedFiles,diffEvidence,createCandidateCommit } from './git.js';import { evaluatePaths } from './policy.js';import { commandEvidence,policyEvidence,diffRecord,sandboxEvidence,evidenceSatisfies } from './evidence.js';import { runShell,now } from './utils.js';import { remoteVerify } from './remote.js';import { lockViolations } from './design-lock.js';
export function verifyTask(taskId,root=process.cwd(),opts={}){
 const s=readState(root);const task=s.tasks.find(t=>t.id===taskId);if(!task)throw new Error(`Unknown task: ${taskId}`);if(task.state!=='IMPLEMENTED')throw new Error(`Task ${taskId} must be IMPLEMENTED before verification (is ${task.state})`);const run=s.runs.filter(r=>r.taskId===taskId).at(-1);if(!run?.worktreePath)throw new Error('No worktree found for latest run');transition(taskId,'VERIFYING',{},root);const files=changedFiles(run.worktreePath);const policy=evaluatePaths(files,task,s.project);const locks=lockViolations(task,files,root);if(locks.length){policy.passed=false;policy.violations.push(...locks.map(x=>({file:'design-lock',reason:x.lockId})));}const evidence=[policyEvidence(taskId,policy),sandboxEvidence(taskId,run.sandbox||{kind:'unknown',level:'worktree'})];let passed=policy.passed;
 if(opts.remoteHost){const remote=remoteVerify(opts.remoteHost,run.worktreePath,task.verification||[]);for(const rr of remote.results){const result={exitCode:rr.exitCode,stdout:rr.stdout,stderr:rr.stderr};const ev=commandEvidence(taskId,rr.command,result);ev.remoteHost=opts.remoteHost;evidence.push(ev);if(result.exitCode!==0)passed=false;}}else{for(const command of task.verification||[]){const r=runShell(command,run.worktreePath,process.env,Number(task.verificationTimeoutMs||s.project.verificationTimeoutMs||15*60*1000));const result={exitCode:r.status??1,stdout:r.stdout||'',stderr:r.stderr||''};evidence.push(commandEvidence(taskId,command,result));if(result.exitCode!==0)passed=false;}}
 if(!(task.verification||[]).length){passed=false;evidence.push({id:`ev-${Date.now()}`,taskId,type:'policy',source:'verification commands required',status:'failed',createdAt:now()});}
 const diff=diffEvidence(run.worktreePath);evidence.push(diffRecord(taskId,diff));const req=evidenceSatisfies(task,evidence);if(!req.passed){passed=false;evidence.push({id:`ev-${Date.now()}-req`,taskId,type:'evidence-requirement',source:'task contract',status:'failed',details:{missing:req.missing},createdAt:now()});}
 recordEvidence(evidence,root);if(passed){const candidate=createCandidateCommit(run.worktreePath,`shipstate(${taskId}): ${task.title}`);if(!candidate){passed=false;evidence.push({id:`ev-${Date.now()}-empty`,taskId,type:'policy',source:'candidate commit',status:'failed',details:'No repository changes',createdAt:now()});recordEvidence([evidence.at(-1)],root);}else{run.candidateCommit=candidate;run.status='verified';recordRun(run,root);}}
 transition(taskId,passed?'VERIFIED':'FAILED',{verifiedAt:passed?now():null,candidateCommit:passed?run.candidateCommit:null},root);return {passed,evidence,candidateCommit:run.candidateCommit||null};
}
