import fs from 'node:fs';import path from 'node:path';import { writeJsonAtomic,readJson,now } from './utils.js';import { initialized,readState } from './store.js';import { chooseNext,eligible } from './core.js';
export function workspaceFile(root=process.cwd()){return path.join(root,'.shipstate-workspace.json');}
export function initWorkspace(name,root=process.cwd()){const w={version:2,name:name||path.basename(root),createdAt:now(),repositories:[],dependencies:[]};writeJsonAtomic(workspaceFile(root),w);return w;}
export function readWorkspace(root=process.cwd()){const w=readJson(workspaceFile(root));if(!w)throw new Error('Workspace not initialized');return {version:2,...w,repositories:w.repositories||[],dependencies:w.dependencies||[]};}
export function addRepository(repoRoot,alias,root=process.cwd()){const w=readWorkspace(root),abs=path.resolve(repoRoot);if(!initialized(abs))throw new Error(`Repository is not SHIPSTATE initialized: ${abs}`);const name=alias||path.basename(abs);if(w.repositories.some(r=>r.alias===name&&r.root!==abs))throw new Error(`Workspace alias already exists: ${name}`);if(!w.repositories.some(r=>r.root===abs))w.repositories.push({alias:name,root:abs});writeJsonAtomic(workspaceFile(root),w);return w;}
function repoBy(w,alias){const r=w.repositories.find(x=>x.alias===alias||x.root===alias);if(!r)throw new Error(`Unknown workspace repository: ${alias}`);return r;}
function parseNode(value){const i=String(value||'').indexOf(':');if(i<1||i===String(value).length-1)throw new Error('Task reference must be <repo-alias>:<TASK-ID>');return {repo:String(value).slice(0,i),taskId:String(value).slice(i+1)};}
function depId(from,to){return `${from.repo}:${from.taskId}->${to.repo}:${to.taskId}`;}
function validateGraph(w){const edges=w.dependencies||[],by=new Map();for(const e of edges){const a=`${e.from.repo}:${e.from.taskId}`,b=`${e.to.repo}:${e.to.taskId}`;(by.get(a)||by.set(a,[]).get(a)).push(b);}const visiting=new Set(),done=new Set();const visit=n=>{if(done.has(n))return;if(visiting.has(n))throw new Error(`Cross-repository dependency cycle at ${n}`);visiting.add(n);for(const x of by.get(n)||[])visit(x);visiting.delete(n);done.add(n);};for(const n of by.keys())visit(n);}
export function addWorkspaceDependency(fromValue,toValue,root=process.cwd()){const w=readWorkspace(root),from=parseNode(fromValue),to=parseNode(toValue),fromRepo=repoBy(w,from.repo),toRepo=repoBy(w,to.repo);from.repo=fromRepo.alias;to.repo=toRepo.alias;const a=readState(fromRepo.root).tasks.find(t=>t.id===from.taskId),b=readState(toRepo.root).tasks.find(t=>t.id===to.taskId);if(!a)throw new Error(`Unknown upstream task ${fromValue}`);if(!b)throw new Error(`Unknown downstream task ${toValue}`);if(from.repo===to.repo&&from.taskId===to.taskId)throw new Error('Cross-repository dependency cannot point to itself');const dependency={id:depId(from,to),from,to,createdAt:now()};if(!w.dependencies.some(x=>x.id===dependency.id))w.dependencies.push(dependency);validateGraph(w);writeJsonAtomic(workspaceFile(root),w);return dependency;}
function crossBlockers(w,repoAlias,taskId,stateByAlias){return (w.dependencies||[]).filter(d=>d.to.repo===repoAlias&&d.to.taskId===taskId).filter(d=>stateByAlias[d.from.repo]?.tasks.find(t=>t.id===d.from.taskId)?.state!=='ACCEPTED').map(d=>({dependencyId:d.id,upstream:`${d.from.repo}:${d.from.taskId}`,state:stateByAlias[d.from.repo]?.tasks.find(t=>t.id===d.from.taskId)?.state||'MISSING'}));}
export function workspaceStatus(root=process.cwd()){const w=readWorkspace(root),stateByAlias={};for(const r of w.repositories)stateByAlias[r.alias]=readState(r.root);const repos=w.repositories.map(r=>{const s=stateByAlias[r.alias],by=Object.fromEntries(s.tasks.map(t=>[t.id,t])),eligibleTasks=s.tasks.filter(t=>eligible(t,by)).map(t=>({...t,crossBlockers:crossBlockers(w,r.alias,t.id,stateByAlias)})),next=eligibleTasks.filter(t=>!t.crossBlockers.length).sort((a,b)=>(b.priority||0)-(a.priority||0)||a.id.localeCompare(b.id))[0]||null;return {...r,project:s.project,next,counts:s.tasks.reduce((a,t)=>(a[t.state]=(a[t.state]||0)+1,a),{}),crossBlocked:eligibleTasks.filter(t=>t.crossBlockers.length).map(t=>({id:t.id,blockers:t.crossBlockers}))};});const next=repos.filter(r=>r.next).sort((a,b)=>(b.next.priority||0)-(a.next.priority||0))[0]||null;return {...w,repositories:repos,next,dependencyStatus:(w.dependencies||[]).map(d=>{const upstream=stateByAlias[d.from.repo]?.tasks.find(t=>t.id===d.from.taskId);return {...d,satisfied:upstream?.state==='ACCEPTED',integratedCommit:upstream?.integratedCommit||null};})};}
