let state=null,view='now',selected=null,token=sessionStorage.getItem('shipstateToken')||'';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{'content-type':'application/json','x-shipstate-token':token,...opts.headers}});const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j;}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600)}
function badge(s){return `<span class="state ${esc(s)}">${esc(s)}</span>`}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}" class="muted">No data</td></tr>`}</tbody></table>`}
function taskRow(t){return `<tr data-task="${esc(t.id)}"><td><b>${esc(t.id)}</b></td><td>${esc(t.title)}</td><td>${badge(t.state)}</td><td>${esc(t.risk||'medium')}</td><td>${esc((t.dependsOn||[]).join(', ')||'—')}</td></tr>`}
function renderNow(){const c=state.counts||{},next=state.next;return `<div class="grid"><div class="card"><span class="muted">Readiness</span><div class="metric">${state.readiness}%</div><div class="bar"><i style="width:${state.readiness}%"></i></div></div><div class="card"><span class="muted">Accepted</span><div class="metric">${c.ACCEPTED||0}</div></div><div class="card"><span class="muted">Blocked / Failed</span><div class="metric">${(c.BLOCKED||0)+(c.FAILED||0)}</div></div><div class="card"><span class="muted">Active runs</span><div class="metric">${state.activeRuns?.length||0}</div></div></div><div class="section-title"><h2>Next action</h2></div><div class="card">${next?`<h3>${esc(next.id)} · ${esc(next.title)}</h3><p>${esc(next.objective)}</p><div class="actions"><button class="primary" data-task="${esc(next.id)}">Open task</button><button data-action="autopilot">Autopilot one task</button></div>`:'<h3>No eligible task</h3><p class="muted">Import/approve work, accept dependencies, or resolve blockers.</p>'}</div><div class="section-title"><h2>Project intelligence</h2></div><div class="card"><p><b>Languages:</b> ${(state.profile?.languages||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')||'—'}</p><p><b>Frameworks:</b> ${(state.profile?.frameworks||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')||'—'}</p><p><b>Detected commands:</b></p><div class="code">${esc(JSON.stringify(state.profile?.commands||{},null,2))}</div></div>`}
function renderTasks(){return `<div class="section-title"><h2>Task graph</h2><button data-action="profile">Refresh profile</button></div>${table(['ID','Task','State','Risk','Dependencies'],(state.tasks||[]).map(taskRow))}`}
function renderRuns(){return `<div class="section-title"><h2>Runs</h2></div>${table(['Run','Task','Agent','Status','Context','Sandbox'],(state.runs||[]).slice().reverse().map(r=>`<tr><td>${esc(r.id)}</td><td>${esc(r.taskId)}</td><td>${esc(r.agent)}</td><td>${esc(r.status)}</td><td>${r.contextTokens||0} tok</td><td>${esc(r.sandbox?.kind||'—')}</td></tr>`))}`}
function renderEvidence(){return `<div class="section-title"><h2>Evidence ledger</h2></div>${table(['Task','Type','Status','Source','Coverage'],(state.evidence||[]).slice().reverse().map(e=>`<tr><td>${esc(e.taskId)}</td><td>${esc(e.type)}</td><td>${esc(e.status)}</td><td>${esc(e.source)}</td><td>${e.coverage??'—'}</td></tr>`))}`}
function renderContext(){const m=state.metrics?.contexts||[];return `<div class="grid"><div class="card"><span class="muted">Context packages</span><div class="metric">${m.length}</div></div><div class="card"><span class="muted">Latest tokens</span><div class="metric">${m.at(-1)?.tokens||0}</div></div><div class="card"><span class="muted">Latest files</span><div class="metric">${m.at(-1)?.selectedFileCount||0}</div></div><div class="card"><span class="muted">Repository files</span><div class="metric">${m.at(-1)?.repositoryFiles||state.profile?.fileCount||0}</div></div></div><div class="section-title"><h2>Context history</h2></div>${table(['Task','Tokens','Files','Budget','Hash'],m.slice().reverse().map(x=>`<tr><td>${esc(x.taskId)}</td><td>${x.tokens}</td><td>${x.selectedFileCount}</td><td>${x.budgetTokens}</td><td>${esc(x.hash.slice(0,10))}</td></tr>`))}`}
function renderSystem(){return `<div class="grid"><div class="card"><h3>Git</h3><div class="code">${esc(JSON.stringify(state.git,null,2))}</div></div><div class="card"><h3>Sandbox</h3><div class="code">${esc(JSON.stringify(state.sandbox,null,2))}</div></div><div class="card"><h3>Journal</h3><div class="code">${esc(JSON.stringify(state.journal,null,2))}</div></div><div class="card"><h3>GitHub</h3><div class="code">${esc(JSON.stringify(state.github,null,2))}</div></div></div><div class="section-title"><h2>Design Locks</h2></div><div class="card">${(state.locks||[]).map(l=>`<p><b>${esc(l.id)}</b> [${esc(l.severity)}] ${esc(l.statement)}</p>`).join('')||'<span class="muted">No locks imported.</span>'}</div><div class="section-title"><h2>Project registry</h2></div>${table(['Name','Root','Last opened'],(state.projects||[]).map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.root)}</td><td>${esc(p.lastOpenedAt)}</td></tr>`))}`}
function render(){if(!state)return;$('#project').textContent=state.project?.name||'SHIPSTATE';$('#subtitle').textContent=`${state.profile?.ecosystems?.join(', ')||'generic'} · ${state.git?.branch||'no branch'}`;$('#ready').textContent=`${state.readiness}%`;$('#content').innerHTML=({now:renderNow,tasks:renderTasks,runs:renderRuns,evidence:renderEvidence,context:renderContext,system:renderSystem}[view]||renderNow)();bindDynamic();}
function bindDynamic(){document.querySelectorAll('[data-task]').forEach(el=>el.onclick=()=>openTask(el.dataset.task));document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action,el.dataset.task));}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;selected=id;$('#drawerBody').innerHTML=`<small>${esc(t.id)}</small><h2>${esc(t.title)}</h2>${badge(t.state)}<p>${esc(t.objective)}</p><h3>Acceptance</h3><ul>${(t.acceptanceCriteria||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Allowed paths</h3><div class="code">${esc((t.allowedPaths||[]).join('\n')||'Unrestricted except protected defaults')}</div><h3>Verification</h3><div class="code">${esc((t.verification||[]).join('\n')||'No commands')}</div><div class="actions"><button data-act="run">Run manual</button><button data-act="verify">Verify</button><button data-act="accept" class="primary">Accept</button><button data-act="reject">Reject</button><button data-act="context">Compile context</button></div>`;$('#drawer').classList.remove('hidden');$('#drawerBody').querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>action(b.dataset.act,id));}
async function action(a,taskId=selected){try{let body={action:a,taskId};if(a==='run')body.agent='manual';if(a==='autopilot')body={action:'autopilot',options:{maxTasks:1,agent:'dry-run',autoAccept:false}};const j=await api('/api/action',{method:'POST',body:JSON.stringify(body)});toast(`${a} complete`);await load();if(taskId&&['run','verify','context'].includes(a))openTask(taskId);return j;}catch(e){toast(e.message)}}
async function load(){state=await api('/api/state');render();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()});$('#refresh').onclick=load;$('#recover').onclick=()=>action('recover');$('#next').onclick=()=>state.next&&openTask(state.next.id);$('#close').onclick=()=>$('#drawer').classList.add('hidden');
if(location.hash.startsWith('#token=')){token=location.hash.slice(7);sessionStorage.setItem('shipstateToken',token);history.replaceState(null,'',location.pathname);}load().catch(e=>toast(e.message));
